// modules/proactive/eventRouter.ts
//
// Section 67 — an event should only wake the detectors that could
// plausibly care about it. OFFER_DEADLINE_APPROACHING must never trigger
// a readiness-anomaly scan across the whole institution. This map is the
// enforcement point; DetectorRegistry.getForEvent() reads it.

export const EVENT_TO_SIGNAL_TYPES: Record<string, string[]> = {
  APPLICATION_SUBMITTED: ['APPLICATION_ELIGIBLE_NOT_APPLIED', 'APPLICATION_RATE_IMPROVED'],
  APPLICATION_DEADLINE_APPROACHING: ['APPLICATION_ELIGIBLE_NOT_APPLIED'],
  DRIVE_PUBLISHED: ['DRIVE_DEADLINE_APPROACHING'],
  DRIVE_DEADLINE_APPROACHING: ['DRIVE_DEADLINE_APPROACHING', 'APPLICATION_ELIGIBLE_NOT_APPLIED'],

  INTERVIEW_COMPLETED: ['INTERVIEW_RESULT_PENDING'],
  RESULT_PUBLISHED: ['INTERVIEW_RESULT_PENDING'],

  OFFER_PUBLISHED: ['OFFER_DEADLINE_APPROACHING'],
  OFFER_DEADLINE_APPROACHING: ['OFFER_DEADLINE_APPROACHING'],
  OFFER_ACCEPTED: ['JOINING_CONFIRMATION_MISSING'],

  JOINING_DATE_APPROACHING: ['JOINING_CONFIRMATION_MISSING'],
  JOINING_CONFIRMATION_SUBMITTED: ['JOINING_CONFIRMATION_MISSING'],

  TRAINING_ASSIGNED: ['TRAINING_LOW_ATTENDANCE'],
  TRAINING_ATTENDANCE_RECORDED: ['TRAINING_LOW_ATTENDANCE'],
  TRAINING_COMPLETED: ['TRAINING_LOW_ATTENDANCE', 'TRAINING_COMPLETION_IMPROVED'],

  READINESS_UPDATED: ['READINESS_SIGNIFICANT_DECLINE', 'READINESS_MILESTONE_REACHED'],
  READINESS_DECLINED: ['READINESS_SIGNIFICANT_DECLINE'],

  INTERVENTION_ASSIGNED: ['INTERVENTION_OVERDUE'],
  INTERVENTION_OVERDUE: ['INTERVENTION_OVERDUE'],

  DATA_QUALITY_ISSUE_CREATED: ['DATA_QUALITY_UNVERIFIED_OUTCOME', 'DATA_QUALITY_ORPHAN_RECORD'],
  PLACEMENT_TARGET_UPDATED: ['MANAGEMENT_PLACEMENT_TARGET_GAP'],
};

export function detectorSignalTypesForEvent(eventType: string): string[] {
  return EVENT_TO_SIGNAL_TYPES[eventType] ?? [];
}
