'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Bookmark, Search, CheckCircle2 } from 'lucide-react';
import { challenges } from '@/lib/challenges';
import { useWorkspace } from '@/lib/state';
import { PageHeading, Empty } from '@/components/ui';
export default function Practice() {
  const { state, update } = useWorkspace(); const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all');
  const solved = new Set(state.attempts.filter(a => a.passed === a.total).map(a => a.challengeId));
  const shown = challenges.filter(c => `${c.title} ${c.skill} ${c.description}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || (filter === 'bookmarks' ? state.bookmarks.includes(c.challengeId) : !solved.has(c.challengeId))));
  return <><PageHeading eyebrow="THINK → WRITE → TEST → IMPROVE" title="One problem. A better programmer." description="Nineteen authored challenges covering real coding patterns, with progressive hints and executable checks."/><div className="toolbar"><label className="search-field"><Search size={17}/><input aria-label="Search challenges" placeholder="Search a problem or skill…" value={search} onChange={e => setSearch(e.target.value)}/></label><select aria-label="Filter challenges" value={filter} onChange={e => setFilter(e.target.value)}><option value="all">All challenges</option><option value="unsolved">Not yet solved</option><option value="bookmarks">Bookmarked</option></select><span className="muted small">{shown.length} challenges</span></div><div className="challenge-list">{shown.map((c, i) => <article className="challenge-card" key={c.challengeId}><span className="challenge-number">{String(i + 1).padStart(2, '0')}</span><div className="challenge-body"><div className="meta-row"><span className="tag violet">{c.difficultyLabel.toLowerCase()}</span><span>{c.taskType.toLowerCase().replaceAll('_', ' ')}</span>{solved.has(c.challengeId) && <span className="cyan"><CheckCircle2 size={14}/>Solved</span>}</div><h2><Link href={`/practice/${c.challengeId}`}>{c.title}</Link></h2><p>{c.learningObjective}</p><div className="meta-row"><span>{c.skill.replaceAll('_', ' ').replace('.', ' / ')}</span><span>{c.difficulty.expectedTimeMinutes} min estimate</span></div></div><div className="challenge-actions"><button className="icon-button" aria-label={`${state.bookmarks.includes(c.challengeId) ? 'Remove bookmark for' : 'Bookmark'} ${c.title}`} aria-pressed={state.bookmarks.includes(c.challengeId)} onClick={() => update(s => ({ ...s, bookmarks: s.bookmarks.includes(c.challengeId) ? s.bookmarks.filter(id => id !== c.challengeId) : [...s.bookmarks, c.challengeId] }))}><Bookmark size={19} fill={state.bookmarks.includes(c.challengeId) ? 'currentColor' : 'none'}/></button><Link className="button secondary" href={`/practice/${c.challengeId}`}>Open <ArrowUpRight size={16}/></Link></div></article>)}</div>{!shown.length && <Empty title="No matching challenges">Try another search or show all challenges.</Empty>}<p className="muted small">JavaScript runs in an isolated browser sandbox. Python and available Java starters support editing and AI mentoring.</p></>;
}
