'use strict';
/**
 * CodeForge AI — Technical Diagnostic domain model
 * ---------------------------------------------------------------
 * Pure data + construction. No adaptive logic, no scoring logic —
 * see adaptive-engine.js for that. This file is what a real
 * "Role Context" service would eventually supply over an API;
 * here it's inlined as a small, deliberately-small, validated seed
 * bank (spec's own instruction: "do not generate hundreds of weak
 * questions" — a handful of good tasks demonstrates the mechanism).
 *
 * Every task is VALIDATED by hand in this file — none of it was
 * generated by an LLM and auto-trusted. See ARCHITECTURE doc,
 * "AI provider architecture", for how a real item pipeline would
 * gate LLM-drafted tasks through DRAFT -> REVIEW -> VALIDATED.
 */

const SKILLS = {
  prog_fund:      { id: 'prog_fund',      name: 'Programming fundamentals' },
  data_handling:  { id: 'data_handling',  name: 'Data handling' },
  algorithms:     { id: 'algorithms',     name: 'Algorithms & DSA' },
  complexity:     { id: 'complexity',     name: 'Complexity reasoning' },
  recursion:      { id: 'recursion',      name: 'Recursion' },
  debugging:      { id: 'debugging',      name: 'Debugging' },
  ml_fund:        { id: 'ml_fund',        name: 'ML fundamentals' },
  tech_reasoning: { id: 'tech_reasoning', name: 'Technical reasoning' },
  apis:           { id: 'apis',           name: 'APIs' },
  sql:            { id: 'sql',            name: 'SQL' },
  databases:      { id: 'databases',      name: 'Databases' },
};

// In a real build this list is owned by the Role Context domain (see
// section 4 of the build prompt: "the diagnostic consumes these, it
// does not duplicate role requirements"). It's inlined here only
// because no Role Context service is reachable from this environment.
const ROLES = {
  ai_ml: {
    id: 'ai_ml',
    name: 'AI / ML Engineer',
    requiredSkills: ['prog_fund', 'algorithms', 'complexity', 'debugging', 'ml_fund', 'tech_reasoning'],
  },
  backend: {
    id: 'backend',
    name: 'Backend Engineer',
    requiredSkills: ['prog_fund', 'apis', 'sql', 'debugging', 'databases'],
  },
};

const LEVELS = ['FOUNDATION', 'DEVELOPING', 'COMPETENT', 'STRONG', 'ADVANCED'];
const TASK_QUALITY_STATUSES = ['DRAFT', 'REVIEW', 'VALIDATED', 'ACTIVE', 'DEPRECATED'];

const CORRECT_WORD_FREQ_CODE = `function wordFrequency(text) {
  const words = text.toLowerCase().match(/[a-z']+/g) || [];
  const freq = {};
  for (const w of words) freq[w] = (freq[w] || 0) + 1;
  return freq;
}`;

const CORRECT_TWO_SUM_CODE = `function twoSum(nums, target) {
  const seen = {};
  for (let i = 0; i < nums.length; i++) {
    const need = target - nums[i];
    if (need in seen) return [seen[need], i];
    seen[nums[i]] = i;
  }
  return [];
}`;

// Q-matrix lives inline on each task as `skills: [{skillId, relationship, weight}]`.
// relationship in PRIMARY | SECONDARY | PREREQUISITE | CONTEXTUAL (spec section 13).
const TASKS = {
  pf_1: {
    id: 'pf_1', version: 1, title: 'Word frequency counter',
    taskType: 'CODING', difficulty: 'FOUNDATION', qualityStatus: 'VALIDATED',
    prompt: 'Write a function wordFrequency(text) that returns an object mapping each lowercase word to how many times it appears. Ignore punctuation.',
    starterCode: 'function wordFrequency(text) {\n  // return an object like { the: 2, cat: 1 }\n}',
    functionName: 'wordFrequency',
    testCases: [
      { args: ['the cat sat on the mat'], expected: { the: 2, cat: 1, sat: 1, on: 1, mat: 1 } },
      { args: ['a a a b b c'], expected: { a: 3, b: 2, c: 1 } },
      { args: ['Hello, hello world!'], expected: { hello: 2, world: 1 }, hidden: true },
    ],
    skills: [
      { skillId: 'prog_fund', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'data_handling', relationship: 'SECONDARY', weight: 0.5 },
    ],
  },
  algo_1: {
    id: 'algo_1', version: 1, title: 'Two sum (indices)',
    taskType: 'CODING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'Write twoSum(nums, target) returning indices [i, j] with i < j of the two numbers that add to target. Exactly one solution exists.',
    starterCode: 'function twoSum(nums, target) {\n  // return [i, j] with i < j\n}',
    functionName: 'twoSum',
    testCases: [
      { args: [[2, 7, 11, 15], 9], expected: [0, 1] },
      { args: [[3, 2, 4], 6], expected: [1, 2] },
      { args: [[1, 5, 3, 7, 9], 16], expected: [3, 4], hidden: true },
    ],
    skills: [
      { skillId: 'algorithms', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'prog_fund', relationship: 'SECONDARY', weight: 0.5 },
      { skillId: 'complexity', relationship: 'CONTEXTUAL', weight: 0.25 },
    ],
    // if evidence for `algorithms` comes back INCORRECT, check the prerequisite
    // before concluding "weak algorithms" (spec sections 23-24).
    prerequisiteCheckTaskId: 'recursion_1',
  },
  complexity_1: {
    id: 'complexity_1', version: 1, title: 'Time complexity of a nested search',
    taskType: 'COMPLEXITY_REASONING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'function hasDuplicatePair(arr) {\n  for (let i = 0; i < arr.length; i++) {\n    for (let j = i + 1; j < arr.length; j++) {\n      if (arr[i] === arr[j]) return true;\n    }\n  }\n  return false;\n}\n\nWhat is the time complexity of hasDuplicatePair, for an array of length n?',
    options: ['O(n)', 'O(n log n)', 'O(n^2)', 'O(2^n)'],
    correctIndex: 2,
    skills: [
      { skillId: 'complexity', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'algorithms', relationship: 'PREREQUISITE', weight: 0.5 },
    ],
    prerequisiteCheckTaskId: 'recursion_1',
  },
  recursion_1: {
    id: 'recursion_1', version: 1, title: 'Tracing a recursive function',
    taskType: 'CODE_READING', difficulty: 'FOUNDATION', qualityStatus: 'VALIDATED',
    prompt: 'function countDown(n) {\n  if (n <= 0) return [];\n  return [n, ...countDown(n - 1)];\n}\n\nWhat does countDown(3) return?',
    options: ['[3, 2, 1]', '[1, 2, 3]', '[3, 2, 1, 0]', 'An infinite loop'],
    correctIndex: 0,
    skills: [{ skillId: 'recursion', relationship: 'PRIMARY', weight: 1 }],
  },
  debug_1: {
    id: 'debug_1', version: 1, title: 'Off-by-one in a running total',
    taskType: 'DEBUGGING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'function sumAll(arr) {\n  let total = 0;\n  for (let i = 0; i <= arr.length; i++) {\n    total += arr[i];\n  }\n  return total;\n}\n\nsumAll([1, 2, 3]) returns NaN instead of 6. What is wrong?',
    options: [
      'The loop condition should be i < arr.length, not i <= arr.length',
      'total should start at 1, not 0',
      'The loop should start at i = 1',
      'total += arr[i] should be total = arr[i]',
    ],
    correctIndex: 0,
    skills: [
      { skillId: 'debugging', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'prog_fund', relationship: 'SECONDARY', weight: 0.5 },
    ],
  },
  ml_1: {
    id: 'ml_1', version: 1, title: 'Bias-variance tradeoff',
    taskType: 'CONCEPTUAL', difficulty: 'EASY', qualityStatus: 'VALIDATED',
    prompt: 'In 2-3 sentences: explain the bias-variance tradeoff and why it matters when choosing a model.',
    skills: [{ skillId: 'ml_fund', relationship: 'PRIMARY', weight: 1 }],
    aiRubric: 'A correct answer explains bias as error from overly simple assumptions (underfitting) and variance as error from sensitivity to the training data (overfitting), and notes total error is minimized somewhere between the two extremes.',
    keyTerms: ['bias', 'variance', 'underfitting', 'overfitting', 'tradeoff', 'balance'],
  },
  ml_2: {
    id: 'ml_2', version: 1, title: 'Diagnosing a generalization gap',
    taskType: 'TECHNICAL_REASONING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'A model reaches 99% accuracy on the training set but 60% on the test set. What is most likely happening, and what would you try first?',
    skills: [
      { skillId: 'ml_fund', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'tech_reasoning', relationship: 'SECONDARY', weight: 0.5 },
    ],
    aiRubric: 'Correctly identifies overfitting, and proposes a reasonable next step: regularization, more data, a simpler model, cross-validation, or a data-leakage check. A misdiagnosis as underfitting, or "just train longer", is a miss.',
    keyTerms: ['overfit', 'regulariz', 'data', 'cross-validation', 'leakage', 'simpler'],
  },
  api_1: {
    id: 'api_1', version: 1, title: 'Reading an Express handler',
    taskType: 'CODE_READING', difficulty: 'EASY', qualityStatus: 'VALIDATED',
    prompt: 'app.get("/users/:id", (req, res) => {\n  const user = findUser(req.params.id);\n  if (!user) {\n    return res.status(404).json({ error: "not found" });\n  }\n  res.json(user);\n});\n\nWhat status code is sent when the user is not found?',
    options: ['200', '400', '404', '500'],
    correctIndex: 2,
    skills: [{ skillId: 'apis', relationship: 'PRIMARY', weight: 1 }],
  },
  sql_1: {
    id: 'sql_1', version: 1, title: 'Query: students above a threshold',
    taskType: 'CODING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'Table students(id, name, cgpa). Write a SQL query returning name and cgpa for every student with cgpa greater than 8, ordered by cgpa descending.',
    skills: [
      { skillId: 'sql', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'databases', relationship: 'SECONDARY', weight: 0.5 },
    ],
    // deterministic clause check, not a live SQL engine — see ARCHITECTURE doc.
    sqlChecks: [
      { pattern: /select/i, label: 'SELECT clause' },
      { pattern: /from\s+students/i, label: 'FROM students' },
      { pattern: /cgpa\s*>\s*8/i, label: 'cgpa > 8 filter' },
      { pattern: /order\s+by\s+cgpa\s+desc/i, label: 'ORDER BY cgpa DESC' },
    ],
  },
  debug_2: {
    id: 'debug_2', version: 1, title: 'Missing await in an async handler',
    taskType: 'DEBUGGING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'app.post("/orders", async (req, res) => {\n  saveOrder(req.body);\n  res.status(201).json({ ok: true });\n});\n// saveOrder is: async function saveOrder(data) { await db.insert(data); }\n\nThe response sometimes returns before the write finishes. What is the bug?',
    options: [
      'saveOrder(req.body) is missing an await',
      'res.status(201) should be res.status(200)',
      'req.body should be req.params',
      'saveOrder should not be async',
    ],
    correctIndex: 0,
    skills: [
      { skillId: 'debugging', relationship: 'PRIMARY', weight: 1 },
      { skillId: 'apis', relationship: 'SECONDARY', weight: 0.5 },
    ],
  },
  db_1: {
    id: 'db_1', version: 1, title: 'When to add an index',
    taskType: 'TECHNICAL_REASONING', difficulty: 'INTERMEDIATE', qualityStatus: 'VALIDATED',
    prompt: 'A students table has 200,000 rows. A query filtering by email is slow. Would you add an index on email? What would you check first, and is there any downside?',
    skills: [{ skillId: 'databases', relationship: 'PRIMARY', weight: 1 }],
    aiRubric: 'Recognizes an index on email would likely help a filter/lookup, mentions checking selectivity or the query plan first, and names a real downside (write/insert overhead, storage, index maintenance). Treating indexes as free with no downside is a miss.',
    keyTerms: ['index', 'select', 'plan', 'cost', 'storage', 'maintenance', 'overhead'],
  },
};

const ROLE_TASK_POOL = {
  ai_ml: ['pf_1', 'algo_1', 'complexity_1', 'debug_1', 'ml_1', 'ml_2', 'recursion_1'],
  backend: ['pf_1', 'api_1', 'sql_1', 'debug_2', 'db_1'],
};

function buildBlueprint(role) {
  const taskBudget = role.id === 'ai_ml' ? 7 : 5;
  return {
    id: `blueprint_${role.id}_v1`,
    roleId: role.id,
    roleVersion: 1,
    version: 1,
    taskBudget,
    timeBudgetMinutes: 12,
    requiredSkills: role.requiredSkills,
    minEvidencePerSkill: 1,
  };
}

function getRoleOrThrow(roleId) {
  const role = ROLES[roleId];
  if (!role) throw new Error(`Unknown roleId: ${roleId}`);
  return role;
}

// Strips answer keys / hidden expectations before a task would ever be sent
// to a client. Deterministic scoring always runs against the full TASKS
// object server-side — only the sanitized view goes over the wire.
function sanitizeTaskForClient(task) {
  const { correctIndex, aiRubric, sqlChecks, prerequisiteCheckTaskId, ...rest } = task;
  const out = { ...rest };
  if (task.testCases) {
    out.testCases = task.testCases.map((tc) =>
      tc.hidden ? { args: tc.args, hidden: true } : { args: tc.args, expected: tc.expected }
    );
  }
  return out;
}

module.exports = {
  SKILLS, ROLES, LEVELS, TASK_QUALITY_STATUSES, TASKS, ROLE_TASK_POOL,
  CORRECT_WORD_FREQ_CODE, CORRECT_TWO_SUM_CODE,
  buildBlueprint, getRoleOrThrow, sanitizeTaskForClient,
};
