'use client';
import Link from 'next/link';
import { ArrowUpRight, Code2, Terminal, GitBranch, CheckCircle2, Clock3, Sparkles } from 'lucide-react';
import { useWorkspace } from '@/lib/state';
import { challenges } from '@/lib/challenges';
import { ActionLink, Empty, PageHeading } from '@/components/ui';
export default function Dashboard() {
  const { state } = useWorkspace(); const solved = new Set(state.attempts.filter(a => a.passed === a.total).map(a => a.challengeId));
  const recent = state.attempts.slice(-3).reverse();
  const lastFailed = [...state.attempts].reverse().find(a => a.passed < a.total && !solved.has(a.challengeId));
  const next = challenges.find(c => c.challengeId === lastFailed?.challengeId) ?? challenges.find(c => !solved.has(c.challengeId)) ?? challenges[0];
  return <><PageHeading eyebrow="LET’S MAKE PROGRESS" title="Build your thinking. Sharpen your code." description="Your next breakthrough starts with one good problem." action={<ActionLink href={`/practice/${next.challengeId}`}>Start practising</ActionLink>}/>
    <div className="dashboard-top"><section className="focus-card"><div className="focus-content"><span className="tag violet"><Sparkles size={13}/> YOUR NEXT CHALLENGE</span><h2>{next.title.replace('Fix: ', '')}</h2><p>{next.learningObjective}</p><div className="meta-row"><span>{next.difficultyLabel.toLowerCase()}</span><span><Clock3 size={14}/>{next.difficulty.expectedTimeMinutes} min estimate</span><span>JavaScript · Python</span></div><ActionLink href={`/practice/${next.challengeId}`}>{lastFailed ? 'Continue working' : 'Open challenge'}</ActionLink></div><div className="code-art" aria-hidden="true"><div className="window-dots"><i/><i/><i/></div><pre><span className="purple">function</span> grow(skill) {'{'}<br/>{'  '}understand();<br/>{'  '}<span className="cyan">try</span> {'{'} build(); {'}'}<br/>{'  '}<span className="purple">catch</span> (mistake) {'{'}<br/>{'    '}learn(mistake);<br/>{'  }'}<br/>{'  '}<span className="cyan">return</span> skill + 1;<br/>{'}'}</pre><span className="art-caption">Every attempt is a step forward.</span></div></section>
    <section className="panel journey-card"><span className="eyebrow">YOUR LEARNING LOOP</span><h3>Progress with purpose.</h3>{['Understand the problem', 'Write your first approach', 'Test, debug, and reflect', 'Solve it independently'].map((s, i) => <div className="journey-step" key={s}><span>{String(i + 1).padStart(2, '0')}</span>{s}</div>)}<p className="muted tiny">Hints help you think. Your work makes it stick.</p></section></div>
    <div className="stats-grid">{[{ label: 'Problems solved', value: solved.size, icon: CheckCircle2 }, { label: 'Practice attempts', value: state.attempts.length, icon: Terminal }, { label: 'Concepts explored', value: state.learned.length, icon: GitBranch }].map(({ label, value, icon: Icon }) => <div className="stat-card" key={label}><span className="stat-icon"><Icon size={19}/></span><div><strong>{value}</strong><span>{label}</span></div><span className="muted tiny">This browser</span></div>)}</div>
    <div className="section-header"><h2>Choose your next move</h2><span className="muted small">Learn by doing</span></div><div className="activity-grid">{[{ href: '/practice', title: 'Solve a problem', copy: 'Build confidence with focused coding challenges.', icon: Code2, tone: 'violet' }, { href: '/debug', title: 'Find the why', copy: 'Untangle an error and improve your next revision.', icon: Terminal, tone: 'cyan' }, { href: '/projects', title: 'Build something real', copy: 'Turn requirements into engineering decisions.', icon: GitBranch, tone: 'amber' }].map(({ href, title, copy, icon: Icon, tone }) => <Link href={href} className="activity-card" key={href}><span className={`activity-icon ${tone}`}><Icon size={23}/></span><ArrowUpRight className="card-arrow" size={19}/><h3>{title}</h3><p>{copy}</p></Link>)}</div>
    <section className="panel recent-panel"><div className="section-header"><h2>Recent work</h2><Link className="text-link" href="/progress">View all activity <ArrowUpRight size={15}/></Link></div>{recent.length ? recent.map(a => <Link className="list-row" href={`/practice/${a.challengeId}`} key={a.id}><Code2 size={18}/><div><strong>{challenges.find(c => c.challengeId === a.challengeId)?.title ?? 'Coding practice'}</strong><p>{new Date(a.at).toLocaleDateString()} · {a.assisted ? 'With guidance' : 'Independent attempt'}</p></div><span className={`tag ${a.passed === a.total ? 'cyan' : ''}`}>{a.passed}/{a.total} checks passed</span><ArrowUpRight size={17}/></Link>) : <Empty title="A fresh page. Your first attempt awaits.">Open a challenge, try an approach, and your coding journey will appear here.</Empty>}</section>
  </>;
}
