import { assessmentTasks } from '@/modules/coding/data/assessment-tasks';
import { assessmentSolutions } from '@/modules/coding/data/assessment-solutions';
import { adaptiveChallenges } from './adaptive';
import { DifficultyLabel, SupportedLanguage, TaskType, TestCategory, type Challenge, type TestCase } from '@/modules/coding/engines/challenges/domain/types';
const adaptations: Record<string, { solution: string; hint: string; complexity: string }> = {
  contains_duplicate: { solution: 'function solve(input) { const nums = input.trim().split(/\\s+/).filter(Boolean).map(Number); return String(new Set(nums).size !== nums.length); }', hint: 'A set keeps only distinct values. Compare its size with the original collection.', complexity: 'O(n)' },
  group_by_signature: { solution: 'function solve(input) { const lines=input.trim().split(/\\r?\\n/);const n=Number(lines[0]);const families=new Set(lines.slice(1,n+1).map(s=>s.split("").sort().join("")));return String(families.size); }', hint: 'Reordering letters does not change the family. Find a canonical signature for each fragment.', complexity: 'O(n · k log k) for n fragments of at most k characters' },
  fibonacci_memo: { solution: 'function solve(input) { const n=Number(input.trim());let a=0,b=1;for(let i=0;i<n;i++){const next=a+b;a=b;b=next;}return String(a); }', hint: 'Reuse the last two Fibonacci values instead of recursively recalculating them.', complexity: 'O(n)' },
  fix_off_by_one: { solution: 'function solve(input) { const [a,b]=input.trim().split(/\\s+/).map(Number);let total=0;for(let i=a;i<=b;i++)total+=i;return String(total); }', hint: 'Inclusive means the final endpoint contributes too. Trace the case a equals b.', complexity: 'O(b − a + 1)' },
  bfs_shortest_path: { solution: 'function solve(input) { const lines=input.trim().split(/\\r?\\n/);const count=Number(lines[0]),adj=new Map();for(const line of lines.slice(1,count+1)){const [a,b]=line.trim().split(/\\s+/);if(!adj.has(a))adj.set(a,[]);if(!adj.has(b))adj.set(b,[]);adj.get(a).push(b);adj.get(b).push(a);}const [start,end]=lines[count+1].trim().split(/\\s+/),queue=[[start,0]],seen=new Set([start]);for(let i=0;i<queue.length;i++){const [node,dist]=queue[i];if(node===end)return String(dist);for(const next of adj.get(node)||[])if(!seen.has(next)){seen.add(next);queue.push([next,dist+1]);}}return "-1"; }', hint: 'Breadth-first search explores increasing distances. Track a distance with each queued node and mark nodes when enqueuing.', complexity: 'O(V + E)' },
};
export const assessmentChallenges: Challenge[] = assessmentTasks.filter(t => adaptations[t.sourceKey]).map(t => {
  const guide = adaptations[t.sourceKey];
  const tests: TestCase[] = t.hidden_tests.map((tc, i) => ({ id: `assessment-${t.sourceKey}-${i}`, input: [tc.input], expectedOutput: tc.expected_output, hidden: i > 0, category: i > 0 ? TestCategory.EDGE : TestCategory.NORMAL, points: 1 }));
  const original = assessmentSolutions[t.sourceKey as keyof typeof assessmentSolutions];
  return { ...adaptiveChallenges[0], challengeId: `assessment-${t.sourceKey}`, title: t.title, description: `${t.statement}\n\nJavaScript contract: define solve(input). Receive the entire input as a string and return the expected output as a string; do not print it. Python uses the original stdin/stdout program contract.`, skill: t.skill.replaceAll('_', ' '), subskill: t.sourceKey, competencies: [t.skill], prerequisites: [], difficultyLabel: t.difficulty === 'easy' ? DifficultyLabel.EASY : DifficultyLabel.INTERMEDIATE, taskType: t.sourceKey === 'fix_off_by_one' ? TaskType.DEBUGGING : TaskType.IMPLEMENTATION, supportedLanguages: [SupportedLanguage.JAVASCRIPT, SupportedLanguage.PYTHON], learningObjective: `Apply ${t.skill.replaceAll('_', ' ')} to a complete input/output problem.`, constraints: ['Follow the input and output format in the problem statement.', 'Return a string in JavaScript. Complexity is discussed, not measured.'], examples: t.public_examples.map(e => ({ input: e.input, output: e.output })), starterCode: { javascript: t.sourceKey === 'fix_off_by_one' ? 'function solve(input) {\n  const [a, b] = input.trim().split(/\\s+/).map(Number);\n  let total = 0;\n  for (let i = a; i < b; i++) total += i;\n  return String(total);\n}' : 'function solve(input) {\n  // Parse the input and return the expected output string.\n  return "";\n}\n', python: t.starter_code }, publicTests: tests.filter(t => !t.hidden), hiddenTests: tests.filter(t => t.hidden), hints: [guide.hint], solutionMetadata: { referenceSolution: { javascript: guide.solution, python: original?.code }, approachSummary: guide.hint, timeComplexity: guide.complexity }, evaluationMetadata: { entryFunction: 'solve', comparisonMode: 'exact' } };
});
