// Section 8 — question lifecycle
export enum LifecycleStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  VALIDATING = 'VALIDATING',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  APPROVED = 'APPROVED',
  PUBLISHED = 'PUBLISHED',
  SUSPENDED = 'SUSPENDED',
  DEPRECATED = 'DEPRECATED',
  RETIRED = 'RETIRED',
  REVALIDATION_REQUIRED = 'REVALIDATION_REQUIRED',
  REJECTED = 'REJECTED',
}

// Section 9 — source provenance
export enum ProvenanceSource {
  HUMAN_AUTHORED = 'HUMAN_AUTHORED',
  AI_GENERATED = 'AI_GENERATED',
  AI_ASSISTED = 'AI_ASSISTED',
  IMPORTED = 'IMPORTED',
  SYSTEM_GENERATED = 'SYSTEM_GENERATED',
  ADAPTED = 'ADAPTED',
  PARTNER_PROVIDED = 'PARTNER_PROVIDED',
}

// Section 10 — internal trust level (never shown raw to students, section 10)
export enum TrustLevel {
  UNVERIFIED = 'UNVERIFIED',
  AUTO_VALIDATED = 'AUTO_VALIDATED',
  REVIEWED = 'REVIEWED',
  APPROVED = 'APPROVED',
  SUSPENDED = 'SUSPENDED',
  RETIRED = 'RETIRED',
}

// Section 43 — question purpose
export enum QuestionPurpose {
  LEARNING = 'LEARNING',
  PRACTICE = 'PRACTICE',
  DIAGNOSTIC = 'DIAGNOSTIC',
  GUIDED = 'GUIDED',
  TRANSFER = 'TRANSFER',
  MASTERY = 'MASTERY',
  TIMED = 'TIMED',
  ASSESSMENT = 'ASSESSMENT',
}

// Section 107 — question health
export enum QuestionHealth {
  HEALTHY = 'HEALTHY',
  WATCH = 'WATCH',
  ANOMALOUS = 'ANOMALOUS',
  SUSPENDED = 'SUSPENDED',
  RETIRED = 'RETIRED',
}

// Section 76 — aggregate quality status (never collapsed to one opaque number, section 75)
export enum QualityStatus {
  PASS = 'PASS',
  PASS_WITH_WARNING = 'PASS_WITH_WARNING',
  NEEDS_REVIEW = 'NEEDS_REVIEW',
  BLOCKED = 'BLOCKED',
  SUSPENDED = 'SUSPENDED',
  RETIRED = 'RETIRED',
}

export enum IssueSeverity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}

// Sections 11/12/26/34/35/40/47/94 — the concrete defect vocabulary used across validators
export enum IssueType {
  SCHEMA_INVALID = 'SCHEMA_INVALID',
  ANSWER_MISMATCH = 'ANSWER_MISMATCH',
  SOLUTION_MISMATCH = 'SOLUTION_MISMATCH',
  MULTIPLE_VALID = 'MULTIPLE_VALID',
  NO_VALID_OPTION = 'NO_VALID_OPTION',
  AMBIGUOUS = 'AMBIGUOUS',
  UNDER_SPECIFIED = 'UNDER_SPECIFIED',
  INTERNAL_CONTRADICTION = 'INTERNAL_CONTRADICTION',
  UNIT_INCONSISTENCY = 'UNIT_INCONSISTENCY',
  SKILL_MISMATCH = 'SKILL_MISMATCH',
  DIFFICULTY_ANOMALY = 'DIFFICULTY_ANOMALY',
  STRUCTURAL_DUPLICATE = 'STRUCTURAL_DUPLICATE',
  DISTRACTOR_QUALITY = 'DISTRACTOR_QUALITY',
  FAIRNESS_CONCERN = 'FAIRNESS_CONCERN',
  ACCESSIBILITY_CONCERN = 'ACCESSIBILITY_CONCERN',
  SECURITY_FAILURE = 'SECURITY_FAILURE',
  VALIDATION_UNAVAILABLE = 'VALIDATION_UNAVAILABLE',
  OTHER = 'OTHER',
}

// Section 52/129 — student-facing report reasons
export enum ReportType {
  ANSWER_WRONG = 'ANSWER_WRONG',
  MULTIPLE_CORRECT = 'MULTIPLE_CORRECT',
  UNCLEAR = 'UNCLEAR',
  MISSING_INFO = 'MISSING_INFO',
  TYPO = 'TYPO',
  DIAGRAM_ISSUE = 'DIAGRAM_ISSUE',
  INAPPROPRIATE = 'INAPPROPRIATE',
  TECHNICAL_ISSUE = 'TECHNICAL_ISSUE',
  OTHER = 'OTHER',
}

// Section 89 — access roles
export enum Role {
  STUDENT = 'STUDENT',
  TRAINER = 'TRAINER',
  CONTENT_REVIEWER = 'CONTENT_REVIEWER',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}

// Section 78 — review workflow actions
export enum ReviewDecision {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  SUSPEND = 'SUSPEND',
  RESTORE = 'RESTORE',
  DEPRECATE = 'DEPRECATE',
  RETIRE = 'RETIRE',
  REQUEST_REVALIDATION = 'REQUEST_REVALIDATION',
}

// Consumed by downstream "Feature 42-52"-style integrations (section 44/60/70) via PublicationService
export enum ProductionMode {
  PRACTICE = 'PRACTICE',
  DIAGNOSTIC = 'DIAGNOSTIC',
  ASSESSMENT = 'ASSESSMENT',
  TIMED_CHALLENGE = 'TIMED_CHALLENGE',
}
