'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Play, Send, Lightbulb, ArrowLeft, ArrowRight, Square } from 'lucide-react';
import { useWorkspace } from '@/lib/state';
import { challenges } from '@/lib/challenges';
import type { Challenge, SupportedLanguage } from '@/engines/challenges/domain/types';
import { Editor } from './editor';
import { Mentor } from './mentor';
import { TextOutput } from './ui';
import type { CheckResult } from '@/runner/sandbox';
export function CodingWorkspace({ challenge: c }: { challenge: Challenge }) {
  const { state, update } = useWorkspace(); const language = c.supportedLanguages.includes(state.language as SupportedLanguage) ? state.language : 'javascript';
  const draftKey = `${c.challengeId}:${language}`; const code = state.drafts[draftKey] ?? c.starterCode[language as SupportedLanguage] ?? '';
  const hints = state.hints[c.challengeId] ?? 0; const [tab, setTab] = useState('problem');
  const [results, setResults] = useState<CheckResult[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [submission, setSubmission] = useState(false); const [checkedCode, setCheckedCode] = useState(''); const [solution, setSolution] = useState(false);
  const worker = useRef<Worker | null>(null); const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  function stop() { worker.current?.terminate(); worker.current = null; if (timer.current) clearTimeout(timer.current); setBusy(false); }
  useEffect(() => () => { worker.current?.terminate(); if (timer.current) clearTimeout(timer.current); }, []);
  function assist() { update(s => ({ ...s, assisted: [...new Set([...s.assisted, c.challengeId])] })); }
  function run(submit: boolean) {
    if (worker.current || language !== 'javascript') return;
    setError(''); setResults([]); setBusy(true); setSubmission(submit); setCheckedCode(code);
    const tests = submit ? [...c.publicTests, ...c.hiddenTests] : c.publicTests;
    const assisted = hints > 0 || state.assisted.includes(c.challengeId);
    try {
      const instance = new Worker('/runner.js'); worker.current = instance;
      timer.current = setTimeout(() => { stop(); setError('Execution exceeded the overall time limit. Check for an infinite loop and try again. No result was recorded.'); }, 15000);
      instance.onerror = () => { stop(); setError('The isolated runner could not load. Reload this page and retry.'); };
      instance.onmessage = (event: MessageEvent<{ results?: CheckResult[]; error?: string }>) => {
        stop(); if (event.data.error || !event.data.results || event.data.results.length !== tests.length) { setError(event.data.error ?? 'The runner returned incomplete checks.'); return; }
        const checked = event.data.results; setResults(checked);
        if (submit) update(s => ({ ...s, attempts: [...s.attempts, { id: crypto.randomUUID(), challengeId: c.challengeId, at: new Date().toISOString(), passed: checked.filter(r => r.passed).length, total: tests.length, assisted: assisted || s.assisted.includes(c.challengeId), languageIssue: checked.every(r => r.status === 'Syntax error'), code }].slice(-100) }));
      };
      instance.postMessage({ code, entry: c.evaluationMetadata.entryFunction, tests, comparison: c.evaluationMetadata.comparisonMode });
    } catch { stop(); setError('This browser could not start the sandbox. Your draft is still saved.'); }
  }
  const next = challenges[(challenges.findIndex(ch => ch.challengeId === c.challengeId) + 1) % challenges.length];
  return <><div className="workspace-heading"><Link className="text-link" href="/practice"><ArrowLeft size={15}/>All challenges</Link><span className="tag violet">{c.difficultyLabel.toLowerCase()}</span><Link className="text-link" href={`/practice/${next.challengeId}`}>Next problem<ArrowRight size={15}/></Link></div><h1 className="challenge-title">{c.title}</h1><p className="subtitle">{c.learningObjective}</p>
  <div className="coding-grid"><section className="problem-panel panel"><div className="tabs" role="tablist" aria-label="Challenge information">{['problem', 'hints', 'approach'].map(t => <button key={t} role="tab" aria-selected={tab === t} className={tab === t ? 'selected' : ''} onClick={() => setTab(t)}>{t}</button>)}</div>{tab === 'problem' ? <div className="problem-content"><TextOutput text={c.description}/>{c.constraints.length > 0 && <><h3>Constraints</h3><ul>{c.constraints.map(s => <li key={s}>{s}</li>)}</ul></>}<h3>Examples</h3>{c.examples.map((ex, i) => <div className="example" key={i}><span className="eyebrow">EXAMPLE {i + 1}</span><pre>Input: {ex.input}<br/>Output: {ex.output}</pre><p>{ex.explanation}</p></div>)}</div> : tab === 'hints' ? <div className="problem-content"><h3>Start small. Keep thinking.</h3><p className="muted">These are authored learning hints. Using a hint marks future attempts on this problem as guided.</p>{c.hints.slice(0, hints).map((h, i) => <div className="hint" key={i}><strong>Hint {i + 1}</strong><p>{h}</p></div>)}<button className="button secondary" disabled={hints >= c.hints.length || busy} onClick={() => update(s => ({ ...s, hints: { ...s.hints, [c.challengeId]: hints + 1 } }))}><Lightbulb size={16}/>{hints >= c.hints.length ? 'All hints revealed' : 'Reveal the next hint'}</button></div> : <div className="problem-content"><label className="field-label">Think before you code<textarea rows={7} placeholder="What is the input? Which data structure fits? What could go wrong?" maxLength={6000} value={state.notes[c.challengeId] ?? ''} onChange={e => update(s => ({ ...s, notes: { ...s.notes, [c.challengeId]: e.target.value } }))}/></label><h3>Compare your approach</h3><p>When you are ready, explore the authored solution. This marks subsequent attempts as guided.</p><button className="button secondary" disabled={busy} onClick={() => { setSolution(!solution); if (!solution) assist(); }}>{solution ? 'Hide solution' : 'Explain the full method'}</button>{solution && <><TextOutput text={c.solutionMetadata.approachSummary}/><pre><code>{c.solutionMetadata.referenceSolution[language as SupportedLanguage] ?? 'An authored reference is not available in this language. Use the explanation above or ask the mentor for a full solution.'}</code></pre><p>{c.solutionMetadata.timeComplexity} time · {c.solutionMetadata.spaceComplexity} space</p></>}</div>}</section>
  <div className="coding-right"><div className="toolbar compact"><label className="inline-label">Language<select value={language} disabled={busy} onChange={e => { update(s => ({ ...s, language: e.target.value as typeof state.language })); setResults([]); }} >{c.supportedLanguages.map(l => <option value={l} key={l}>{l}</option>)}</select></label><span className="tag">{language === 'javascript' ? 'ISOLATED RUNNER' : 'EDITOR + MENTOR'}</span></div><Editor code={code} language={language} disabled={busy} onChange={value => update(s => ({ ...s, drafts: { ...s.drafts, [draftKey]: value } }))} onReset={() => { update(s => ({ ...s, drafts: { ...s.drafts, [draftKey]: c.starterCode[language as SupportedLanguage] ?? '' } })); setResults([]); }}/><div className="run-bar"><span className="muted tiny">{language === 'javascript' ? 'Run examples, then submit all practice checks.' : 'Live execution is available for JavaScript only.'}</span>{busy ? <button className="button secondary" onClick={() => { stop(); setError('Run cancelled. No attempt recorded.'); }}><Square size={14}/>Stop run</button> : <><button className="button secondary" disabled={language !== 'javascript' || !code.trim()} onClick={() => run(false)}><Play size={14}/>Run examples</button><button className="button" disabled={language !== 'javascript' || !code.trim()} onClick={() => run(true)}><Send size={14}/>Submit attempt</button></>}</div>
    <section className="console-panel" aria-live="polite"><div className="panel-title"><h3>Test results</h3><span className="tag">{submission ? 'ALL PRACTICE CHECKS' : 'EXAMPLES'}</span></div>{busy ? <p className="loading">Running in the sandbox…</p> : error ? <p className="notice" role="alert">{error}</p> : results.length ? <><p className={results.every(r => r.passed) ? 'cyan' : 'amber'}>{results.filter(r => r.passed).length} / {results.length} checks passed {submission && results.every(r => r.passed) ? '· Accepted for this practice set' : ''}</p>{checkedCode !== code && <p className="notice">Your code changed. These results belong to the previous draft.</p>}{results.map(r => <details className="test-row" key={r.id}><summary><span className={r.passed ? 'cyan' : 'amber'}>{r.passed ? '✓' : '×'} {r.status}</span><span>{r.note}</span></summary><pre>Expected: {JSON.stringify(r.expected)?.slice(0, 2500)}<br/>Returned: {JSON.stringify(r.actual)?.slice(0, 2500) ?? 'No result'}{r.error && `\n${r.error}`}</pre></details>)}</> : <p className="muted">Your results will appear here after a run. No checks have run yet.</p>}<p className="muted tiny">Local practice checks are visible in this browser; passing them is not a proof of correctness or complexity.</p></section>
    <Mentor key={`${c.challengeId}:${language}`} code={code} context={`${c.description}\nStudent reasoning: ${state.notes[c.challengeId] ?? ''}\nLast actual checks: ${JSON.stringify(results).slice(0, 3000)}`} language={language} onAssist={assist}/></div></div></>;
}
