"""part 2: companies drives applications interviews offers

Revision ID: 7b6a5c033ed6
Revises: 1ba39f1db191
Create Date: 2026-08-14 02:00:57.557812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b6a5c033ed6'
down_revision: Union[str, Sequence[str], None] = '1ba39f1db191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('pipeline_stage', sa.Enum('PROSPECT', 'CONTACTED', 'INTERESTED', 'REQUIREMENT_RECEIVED', 'DRIVE_SCHEDULED', 'DRIVE_COMPLETED', 'HIRING', 'REPEAT_RECRUITER', name='pipeline_stage'), nullable=False),
    sa.Column('recruiter_owner_user_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recruiter_owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name', name='uq_company_institution_name')
    )
    op.create_index(op.f('ix_companies_institution_id'), 'companies', ['institution_id'], unique=False)
    op.create_table('company_contacts',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_contacted_at', sa.Date(), nullable=True),
    sa.Column('next_follow_up_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_contacts_company_id'), 'company_contacts', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_contacts_institution_id'), 'company_contacts', ['institution_id'], unique=False)
    op.create_table('drives',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('ctc_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'UPCOMING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='drive_status'), nullable=False),
    sa.Column('min_cgpa', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('max_backlogs', sa.Integer(), nullable=False),
    sa.Column('eligible_department_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('drive_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['placement_seasons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drives_company_id'), 'drives', ['company_id'], unique=False)
    op.create_index(op.f('ix_drives_institution_id'), 'drives', ['institution_id'], unique=False)
    op.create_index(op.f('ix_drives_season_id'), 'drives', ['season_id'], unique=False)
    op.create_table('applications',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEWING', 'SELECTED', 'REJECTED', 'WITHDRAWN', name='application_stage'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_id', 'student_id', name='uq_application_drive_student')
    )
    op.create_index(op.f('ix_applications_drive_id'), 'applications', ['drive_id'], unique=False)
    op.create_index(op.f('ix_applications_institution_id'), 'applications', ['institution_id'], unique=False)
    op.create_index(op.f('ix_applications_student_id'), 'applications', ['student_id'], unique=False)
    op.create_table('interview_rounds',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('drive_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['drive_id'], ['drives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_rounds_drive_id'), 'interview_rounds', ['drive_id'], unique=False)
    op.create_index(op.f('ix_interview_rounds_institution_id'), 'interview_rounds', ['institution_id'], unique=False)
    op.create_table('interview_schedules',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'COMPLETED', 'NO_SHOW', 'CANCELLED', name='schedule_status'), nullable=False),
    sa.Column('result', sa.Enum('PENDING', 'PASS_', 'FAIL', name='round_result'), nullable=False),
    sa.Column('interviewer_name', sa.String(length=255), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['interview_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_schedules_application_id'), 'interview_schedules', ['application_id'], unique=False)
    op.create_index(op.f('ix_interview_schedules_institution_id'), 'interview_schedules', ['institution_id'], unique=False)
    op.create_index(op.f('ix_interview_schedules_round_id'), 'interview_schedules', ['round_id'], unique=False)
    op.create_table('offers',
    sa.Column('institution_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ctc_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('EXTENDED', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', 'JOINED', name='offer_status'), nullable=False),
    sa.Column('extended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('joining_confirmed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offers_application_id'), 'offers', ['application_id'], unique=True)
    op.create_index(op.f('ix_offers_company_id'), 'offers', ['company_id'], unique=False)
    op.create_index(op.f('ix_offers_institution_id'), 'offers', ['institution_id'], unique=False)
    op.create_index(op.f('ix_offers_student_id'), 'offers', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_student_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_institution_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_company_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_application_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_interview_schedules_round_id'), table_name='interview_schedules')
    op.drop_index(op.f('ix_interview_schedules_institution_id'), table_name='interview_schedules')
    op.drop_index(op.f('ix_interview_schedules_application_id'), table_name='interview_schedules')
    op.drop_table('interview_schedules')
    op.drop_index(op.f('ix_interview_rounds_institution_id'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_drive_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    op.drop_index(op.f('ix_applications_student_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_institution_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_drive_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_drives_season_id'), table_name='drives')
    op.drop_index(op.f('ix_drives_institution_id'), table_name='drives')
    op.drop_index(op.f('ix_drives_company_id'), table_name='drives')
    op.drop_table('drives')
    op.drop_index(op.f('ix_company_contacts_institution_id'), table_name='company_contacts')
    op.drop_index(op.f('ix_company_contacts_company_id'), table_name='company_contacts')
    op.drop_table('company_contacts')
    op.drop_index(op.f('ix_companies_institution_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # See Part 1's migration for why this is necessary: autogenerate
    # creates Postgres ENUM types implicitly but never drops them.
    for enum_name in (
        "pipeline_stage", "drive_status", "application_stage",
        "schedule_status", "round_result", "offer_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
