'use strict';

const STATES = [
  'DISCOVERED', 'REVIEWED', 'ELIGIBILITY_CHECKED', 'PREPARING', 'READY',
  'APPLIED', 'ASSESSMENT', 'INTERVIEW', 'FINAL_STAGE',
  'WITHDRAWN', 'EXPIRED', 'REJECTED', 'SELECTED', 'UNKNOWN',
];

// spec section 43: DISCOVERED -> ... -> OUTCOME, with WITHDRAWN/EXPIRED/
// REJECTED/SELECTED/UNKNOWN allowed where appropriate rather than forced
// through every intermediate stage.
const TRANSITIONS = {
  DISCOVERED: ['REVIEWED', 'WITHDRAWN', 'EXPIRED'],
  REVIEWED: ['ELIGIBILITY_CHECKED', 'WITHDRAWN', 'EXPIRED'],
  ELIGIBILITY_CHECKED: ['PREPARING', 'READY', 'WITHDRAWN', 'EXPIRED'],
  PREPARING: ['READY', 'WITHDRAWN', 'EXPIRED'],
  READY: ['APPLIED', 'WITHDRAWN', 'EXPIRED'],
  APPLIED: ['ASSESSMENT', 'INTERVIEW', 'REJECTED', 'WITHDRAWN', 'UNKNOWN'],
  ASSESSMENT: ['INTERVIEW', 'REJECTED', 'WITHDRAWN', 'UNKNOWN'],
  INTERVIEW: ['FINAL_STAGE', 'REJECTED', 'SELECTED', 'WITHDRAWN', 'UNKNOWN'],
  FINAL_STAGE: ['SELECTED', 'REJECTED', 'WITHDRAWN', 'UNKNOWN'],
  WITHDRAWN: [],
  EXPIRED: [],
  REJECTED: [],
  SELECTED: [],
  UNKNOWN: ['APPLIED', 'ASSESSMENT', 'INTERVIEW', 'FINAL_STAGE', 'REJECTED', 'SELECTED'],
};

function canTransition(from, to) {
  return Boolean(TRANSITIONS[from] && TRANSITIONS[from].includes(to));
}

module.exports = { STATES, TRANSITIONS, canTransition };
