import { CHALLENGES, SKILLS, RELATIONSHIPS } from '@/data/adaptive-challenges';
import { ChallengeLifecycleStatus, DifficultyLabel, ProgressionStage, RoleContext, SupportedLanguage, TaskType, TestCategory, type Challenge, type TestCase } from '@/engines/challenges/domain/types';
const helpers: Record<string, { args: string; hint: string; solution: string; approach: string; time: string; space: string }> = {
  twoSum: { args: 'nums, target', hint: 'For each number, look for its complement among numbers already visited.', solution: 'function twoSum(nums, target) { const seen = new Map(); for (let i = 0; i < nums.length; i++) { const j = seen.get(target - nums[i]); if (j !== undefined) return [j, i]; seen.set(nums[i], i); } return []; }', approach: 'Index earlier values in a map. Check the complement before inserting the current value to avoid reusing an index.', time: 'O(n)', space: 'O(n)' },
  isValidParentheses: { args: 's', hint: 'The most recently opened bracket must be the first one closed.', solution: 'function isValidParentheses(s) { const stack = [], pairs = { ")": "(", "]": "[", "}": "{" }; for (const c of s) { if ("([{”.includes(c)) stack.push(c); else if (stack.pop() !== pairs[c]) return false; } return stack.length === 0; }'.replace('”', '"'), approach: 'Push opening brackets onto a stack. Every closing bracket must match the top; the stack must be empty at the end.', time: 'O(n)', space: 'O(n)' },
  binarySearch: { args: 'nums, target', hint: 'Keep an interval that can still contain the target. Each comparison removes half.', solution: 'function binarySearch(nums, target) { let lo=0, hi=nums.length-1; while(lo<=hi) { const m=lo+Math.floor((hi-lo)/2); if(nums[m]===target) return m; if(nums[m]<target) lo=m+1; else hi=m-1; } return -1; }', approach: 'Compare the middle element against the target and retain only the relevant half of the sorted interval.', time: 'O(log n)', space: 'O(1)' },
  searchRotated: { args: 'nums, target', hint: 'Even after rotation, at least one half around the midpoint remains sorted.', solution: 'function searchRotated(nums,target){let lo=0,hi=nums.length-1;while(lo<=hi){const m=lo+Math.floor((hi-lo)/2);if(nums[m]===target)return m;if(nums[lo]<=nums[m]){if(nums[lo]<=target&&target<nums[m])hi=m-1;else lo=m+1;}else{if(nums[m]<target&&target<=nums[hi])lo=m+1;else hi=m-1;}}return -1;}', approach: 'Identify the sorted half. If the target falls inside its range, search there; otherwise use the other half.', time: 'O(log n)', space: 'O(1)' },
  maxProfit: { args: 'prices', hint: 'Track the lowest price before today. What profit would selling today produce?', solution: 'function maxProfit(prices){let low=Infinity,best=0;for(const price of prices){best=Math.max(best,price-low);low=Math.min(low,price);}return best;}', approach: 'Maintain the cheapest earlier purchase and the best profit seen so far. Do not allow selling before buying.', time: 'O(n)', space: 'O(1)' },
  lengthOfLongestSubstring: { args: 's', hint: 'Grow a window of unique characters. Move its left edge past a repeated character.', solution: 'function lengthOfLongestSubstring(s){const last=new Map();let left=0,best=0;for(let right=0;right<s.length;right++){if(last.has(s[right]))left=Math.max(left,last.get(s[right])+1);last.set(s[right],right);best=Math.max(best,right-left+1);}return best;}', approach: 'A sliding window maintains uniqueness, while a map records the last index of each character. Never move the left boundary backward.', time: 'O(n)', space: 'O(k)' },
  MyQueue: { args: '', hint: 'Push into one stack. Transfer to the other only when that second stack is empty.', solution: 'class MyQueue { constructor(){this.input=[];this.output=[];} push(x){this.input.push(x);} transfer(){if(!this.output.length)while(this.input.length)this.output.push(this.input.pop());} pop(){this.transfer();return this.output.pop()??null;} peek(){this.transfer();return this.output[this.output.length-1]??null;} isEmpty(){return !this.input.length&&!this.output.length;} }', approach: 'Two reversals preserve FIFO order. Each element transfers at most once, giving amortized constant time per operation.', time: 'O(1) amortized per operation', space: 'O(n)' },
  bfsOrder: { args: 'n, edges, start', hint: 'Use a queue and mark a node visited when it is enqueued, not when it is removed.', solution: 'function bfsOrder(n,edges,start){const adj=Array.from({length:n},()=>[]);for(const [a,b] of edges){adj[a].push(b);adj[b].push(a);}const queue=[start],seen=new Set(queue);for(let i=0;i<queue.length;i++){for(const v of adj[queue[i]])if(!seen.has(v)){seen.add(v);queue.push(v);}}return queue;}', approach: 'Build adjacency lists, then process a FIFO frontier. Preserve edge insertion order and visit each reachable node once.', time: 'O(V + E)', space: 'O(V + E)' },
  climbingStairs: { args: 'n', hint: 'The last move came from one step below or two steps below. Combine those counts.', solution: 'function climbingStairs(n){let a=1,b=1;for(let i=2;i<=n;i++){const next=a+b;a=b;b=next;}return b;}', approach: 'The recurrence ways(n)=ways(n-1)+ways(n-2) needs only the two previous counts.', time: 'O(n)', space: 'O(1)' },
};
export const adaptiveChallenges: Challenge[] = CHALLENGES.filter(c => c.functionName !== 'word_frequency').map(c => {
  const h = helpers[c.functionName];
  const tests: TestCase[] = c.testCases.filter(t => t.language === 'javascript').map(t => ({ id: t.id, category: t.category === 'edge' ? TestCategory.EDGE : TestCategory.NORMAL, input: Array.isArray(t.input) ? t.input : [t.input], expectedOutput: t.expected, hidden: !!t.isHidden, points: 1, note: t.category }));
  const prompt = c.prompt + (c.harnessType === 'stateful_ops' ? ' Define a class MyQueue. Empty pop/peek returns null; push returns no value. The checks invoke each operation in order.' : '') + (c.functionName === 'bfsOrder' ? ' Visit neighbors in the order edges are provided.' : '') + (c.functionName === 'twoSum' ? ' Exactly one pair exists; return the smaller index first.' : '');
  return { challengeId: c.id, version: 1, title: c.title, description: prompt, roleContext: [RoleContext.GENERAL_SWE], skill: SKILLS.find(s => s.id === c.primarySkill)?.name ?? c.primarySkill, subskill: c.primarySkill, competencies: c.secondarySkills ?? [], prerequisites: RELATIONSHIPS.filter(r => r.to === c.primarySkill && r.type === 'PREREQUISITE').map(r => SKILLS.find(s => s.id === r.from)?.name ?? r.from), difficulty: { conceptualComplexity: c.conceptDifficulty, implementationComplexity: c.implementationComplexity, reasoningComplexity: c.reasoningComplexity, edgeCaseComplexity: c.constraintComplexity, prerequisiteDepth: 1, expectedTimeMinutes: 20, calibrated: false }, difficultyLabel: c.difficultyLevel === 'EASY' ? DifficultyLabel.EASY : c.difficultyLevel === 'MEDIUM' ? DifficultyLabel.INTERMEDIATE : DifficultyLabel.ADVANCED, progressionStage: ProgressionStage.BASIC_APPLICATION, taskType: TaskType.IMPLEMENTATION, supportedLanguages: c.languages as SupportedLanguage[], learningObjective: `Practise ${SKILLS.find(s => s.id === c.primarySkill)?.name.toLowerCase() ?? 'problem solving'} through ${c.title.toLowerCase()}.`, constraints: ['Inputs follow the problem statement.', 'Practice checks validate output, not the claimed complexity.'], examples: tests.slice(0, 2).map(t => ({ input: JSON.stringify(t.input), output: JSON.stringify(t.expectedOutput) })), starterCode: { javascript: c.harnessType === 'stateful_ops' ? 'class MyQueue {\n  constructor() {}\n  push(x) {}\n  pop() { return null; }\n  peek() { return null; }\n  isEmpty() { return true; }\n}' : `function ${c.functionName}(${h.args}) {\n  // Start with a clear approach.\n}\n`, ...(c.languages.includes('python') ? { python: `def ${c.functionName}(${h.args}):\n    pass\n` } : {}) }, publicTests: tests.filter(t => !t.hidden), hiddenTests: tests.filter(t => t.hidden), hints: [h.hint], solutionMetadata: { referenceSolution: { javascript: h.solution }, approachSummary: h.approach, timeComplexity: h.time, spaceComplexity: h.space }, evaluationMetadata: { entryFunction: c.functionName, comparisonMode: 'exact' }, qualityStatus: ChallengeLifecycleStatus.ACTIVE, qualityAnalytics: null, createdAt: '', updatedAt: '' };
});
