import { MasteryEvidenceRecord, Skill } from "../domain/types";

/**
 * §46 — Feature 5 talks to Feature 3 (Skill Intelligence) and Feature 4
 * (Mastery Path) ONLY through these two interfaces. Nothing else in this
 * codebase imports a concrete Feature 3/4 client directly. When those
 * features exist for real, replace the two InMemoryStub* implementations
 * below with real HTTP/RPC clients — nothing upstream of the adapter needs
 * to change.
 */

export interface SkillIntelligenceAdapter {
  /** Pull the current skill catalog + prerequisite graph that Feature 3 owns. */
  getSkillCatalog(): Promise<Skill[]>;
  /** Feature 3 may flag a skill as already known-weak from other evidence (interviews, past terms, etc.) — Feature 5 should weight session planning toward these when present. */
  getExternallyFlaggedWeakSkills(studentId: string): Promise<string[]>;
}

export interface MasteryPathAdapter {
  /** Push new performance evidence generated by Feature 5 up to Feature 4 for path replanning. */
  submitPerformanceEvidence(studentId: string, evidence: MasteryEvidenceRecord[]): Promise<void>;
  /** Ask Feature 4 whether a given skill is currently on the student's active mastery path (vs. out of scope). */
  isSkillOnActivePath(studentId: string, skillId: string): Promise<boolean>;
}

/**
 * Stand-in used until real Feature 3/4 services exist. Returns the local
 * skill catalog Feature 5 seeded itself and treats every skill as
 * in-scope/no-external-flags. Swap this binding in services/practiceOrchestrator.ts
 * once real adapters are available — no other file needs to change.
 */
export class InMemorySkillIntelligenceAdapter implements SkillIntelligenceAdapter {
  constructor(private readonly getLocalCatalog: () => Skill[]) {}

  async getSkillCatalog(): Promise<Skill[]> {
    return this.getLocalCatalog();
  }

  async getExternallyFlaggedWeakSkills(_studentId: string): Promise<string[]> {
    return [];
  }
}

export class InMemoryMasteryPathAdapter implements MasteryPathAdapter {
  async submitPerformanceEvidence(_studentId: string, _evidence: MasteryEvidenceRecord[]): Promise<void> {
    // No-op placeholder — real implementation POSTs to Feature 4's evidence intake endpoint.
    return;
  }

  async isSkillOnActivePath(_studentId: string, _skillId: string): Promise<boolean> {
    return true;
  }
}
