import { Trace } from "@/engines/incidents/types";

export const traces: Trace[] = [
  {
    traceKey: "trace-baseline-01",
    label: "Baseline request (pre-incident, healthy)",
    offsetSeconds: -25 * 60,
    totalDurationMs: 175,
    status: "SUCCESS",
    spans: [
      {
        spanKey: "s1",
        serviceKey: "web-frontend",
        operation: "submit_application (client)",
        startOffsetMs: 0,
        durationMs: 15,
        status: "OK",
      },
      {
        spanKey: "s2",
        parentSpanKey: "s1",
        serviceKey: "api-gateway",
        operation: "POST /api/applications/submit",
        startOffsetMs: 5,
        durationMs: 165,
        status: "OK",
      },
      {
        spanKey: "s3",
        parentSpanKey: "s2",
        serviceKey: "placement-api",
        operation: "handle_submit_application",
        startOffsetMs: 15,
        durationMs: 145,
        status: "OK",
      },
      {
        spanKey: "s4",
        parentSpanKey: "s3",
        serviceKey: "placement-db",
        operation: "query: check_employer_verification_status",
        startOffsetMs: 25,
        durationMs: 8,
        status: "OK",
      },
      {
        spanKey: "s5",
        parentSpanKey: "s3",
        serviceKey: "placement-db",
        operation: "query: insert_application",
        startOffsetMs: 40,
        durationMs: 38,
        status: "OK",
      },
    ],
  },
  {
    traceKey: "trace-incident-01",
    label: "Failing request (during incident)",
    offsetSeconds: -5 * 60,
    totalDurationMs: 4650,
    status: "ERROR",
    spans: [
      {
        spanKey: "s1",
        serviceKey: "web-frontend",
        operation: "submit_application (client)",
        startOffsetMs: 0,
        durationMs: 10,
        status: "OK",
      },
      {
        spanKey: "s2",
        parentSpanKey: "s1",
        serviceKey: "api-gateway",
        operation: "POST /api/applications/submit",
        startOffsetMs: 8,
        durationMs: 4630,
        status: "ERROR",
      },
      {
        spanKey: "s3",
        parentSpanKey: "s2",
        serviceKey: "placement-api",
        operation: "handle_submit_application",
        startOffsetMs: 20,
        durationMs: 4600,
        status: "ERROR",
      },
      {
        spanKey: "s4",
        parentSpanKey: "s3",
        serviceKey: "placement-db",
        operation: "query: check_employer_verification_status (JOIN employers)",
        startOffsetMs: 35,
        durationMs: 4550,
        status: "SLOW",
      },
    ],
  },
];
