'use client';
import { useWorkspace } from '@/lib/state';
import project from '@/data/notification-project.json';
import { PageHeading } from '@/components/ui';
import { Editor } from '@/components/editor';
import { Mentor } from '@/components/mentor';
const steps = ['Clarify delivery, retry, and ordering assumptions', 'Design the event API and authorization boundary', 'Implement idempotent notification handling', 'Design tests for retries, failures, and concurrency', 'Document architecture and operating decisions'];
export default function Projects() {
  const { state, update } = useWorkspace(); const code = state.drafts.project ?? '';
  return <><PageHeading eyebrow="FROM REQUIREMENTS TO REASONING" title={project.title} description={project.requirements.businessGoal}/><div className="two-columns"><div><section className="panel"><div className="meta-row"><span className="tag violet">{project.difficulty}</span><span>{project.timeEstimateMinutes} min estimate</span><span>Backend engineering</span></div><h2>Project brief</h2>{[['Functional requirements', project.requirements.functionalRequirements], ['Reliability', project.requirements.nonFunctionalRequirements], ['Edge cases', project.requirements.edgeCases], ['Security', project.securityRequirements]].map(([title, items]) => <div key={title as string}><h3>{title}</h3><ul>{(items as string[]).map(s => <li key={s}>{s}</li>)}</ul></div>)}<details><summary>Acceptance criteria and review rubric</summary>{project.acceptanceCriteria.map(c => <p key={c.id}>{c.description} <span className="muted">Expected: {c.expectedBehavior}</span></p>)}<p>{project.rubric.categories.map(c => `${c.label} (${c.weight}%)`).join(' · ')}</p></details></section><section className="panel"><h3>Build checklist</h3><p className="muted small">{state.projectSteps.length} of {steps.length} self-recorded steps. These checkboxes are not automated acceptance tests.</p><progress max={steps.length} value={state.projectSteps.length} aria-label="Self-recorded project steps"/>{steps.map((s, i) => <label className="check-row" key={s}><input type="checkbox" checked={state.projectSteps.includes(String(i))} onChange={() => update(st => ({ ...st, projectSteps: st.projectSteps.includes(String(i)) ? st.projectSteps.filter(id => id !== String(i)) : [...st.projectSteps, String(i)] }))}/>{s}</label>)}</section></div><div><label className="field-label">Architecture and decisions<textarea rows={7} maxLength={6000} placeholder="My delivery model, idempotency key, retry policy, and trade-offs…" value={state.notes.project ?? ''} onChange={e => update(s => ({ ...s, notes: { ...s.notes, project: e.target.value } }))}/></label><Editor code={code} language="javascript" onChange={v => update(s => ({ ...s, drafts: { ...s.drafts, project: v } }))} onReset={() => update(s => ({ ...s, drafts: { ...s.drafts, project: '' } }))}/><p className="muted small">Use this scratchpad for a focused implementation. Full service execution and deployment are outside this project lab.</p><Mentor initialMode="project" code={code} context={`${JSON.stringify(project.requirements)}\nStudent decisions: ${state.notes.project ?? ''}`}/></div></div></>;
}
