import sys
text = """
---

## Frontend UI (`frontend/src/`)

### `frontend/src/app/page.tsx` & `frontend/src/app/layout.tsx`
**Level:** UI Entry Point
These are the root Next.js pages representing the public unauthenticated landing page and the global HTML wrapper. `page.tsx` drives conversion by communicating the product value visually, while `layout.tsx` injects global fonts, stylesheets, and meta tags necessary for SEO and consistent styling.

### `frontend/src/app/admin/*` & `frontend/src/app/org-admin/*`
**Level:** B2B / Admin Dashboard UI
These React components render the "God-mode" tools for founders and organizational leaders. They include data tables for managing student cohorts (`students/page.tsx`), analytics visualizations (`analytics/page.tsx`), and support chat interfaces. They interact strictly with the protected `/api/org-admin` and `/api/admin` backend routers.

### `frontend/src/app/interview/[id]/page.tsx`
**Level:** Complex UI Client
This is the most technically complex client-side component. It handles the real-time mock interview by orchestrating the Web Speech API (for STT/TTS) and managing state machines (e.g., 'USER_SPEAKING' vs 'AI_SPEAKING'). It also handles client-side speech normalization and sends heartbeat telemetry to the backend.

### `frontend/src/app/dashboard/page.tsx` & `frontend/src/app/student-dashboard/page.tsx`
**Level:** Core Authenticated UI
These files act as the primary home base for logged-in users. They render the candidate's history, active plan usage, and high-level progress charts. They pull consolidated data from the backend to give the user an immediate sense of their standing and prompt them to start their next session.

### `frontend/src/app/login/page.tsx`
**Level:** Authentication UI
This handles the user-facing login and signup flows. It contains logic to request email OTPs, verify them, or trigger Google OAuth popups. It bridges the visual interface to the `AuthContext` provider, ensuring a frictionless onboarding experience.

### `frontend/src/app/analytics/page.tsx`
**Level:** Data Visualization UI
This page renders deep, category-level skill insights for the individual student. It uses charting libraries to plot their progress over time, visualize their weakest technical areas, and display the personalized coaching feedback generated by the backend analytics engine.

### `frontend/src/components/*.tsx` (incl. `difficulty-selector.tsx`, `plan-selector.tsx`, `ambient-effects.tsx`)
**Level:** Reusable UI Modules
These are the granular building blocks of the UI. Files like `difficulty-selector.tsx` handle standard form inputs with customized logic, while `ambient-effects.tsx` drives dynamic background visual flares (like glow effects tracking the mouse cursor) to make the application feel premium and responsive.

### `frontend/src/lib/api.ts` & `frontend/src/lib/auth-context.tsx`
**Level:** Client Data Layer
These form the central nervous system connecting the React UI to the Python backend. `api.ts` provides a robust, typed fetch wrapper that automatically handles JWT injection and error catching. `auth-context.tsx` maintains the global React Context for the logged-in user, making profile data instantly available to any nested component.

### `frontend/src/lib/plan-usage.ts`
**Level:** Client Logic
This library mirrors the backend consumption rules. It computes how many interviews a user has left based on their current plan, driving the UI state (e.g., locking the "Start" button if limits are hit) without needing to poll the backend constantly.

### `frontend/next.config.ts`, `frontend/eslint.config.mjs`, `frontend/postcss.config.mjs`
**Level:** Frontend Tooling
These configuration files dictate how the Next.js application is built, linted, and styled. They configure standard behavior like CSS module resolution, routing rewrites (if any), and code quality enforcement, ensuring clean production builds.

---

## Infrastructure Scripts (`scripts/`)

### `scripts/ast_extractor.py`, `scripts/ts_extractor.py`, `scripts/gen_other_docs.py`
**Level:** Tooling / Meta-programming
These utility scripts parse the codebase itself. They extract class and function signatures using AST (Abstract Syntax Trees) or RegEx to automatically generate documentation, map the project structure, or aid LLMs in understanding the application.

### `scripts/staging_smoke.py`
**Level:** QA / Testing
This script automates smoke testing against a live staging environment. It typically hits key endpoints, simulates a basic interview loop, and asserts that the production build is structurally sound before it gets promoted to the live user traffic servers.

### `scripts/append_chunk*.py`
**Level:** One-off Utility
These are transient scripts likely used to batch process large texts, append data chunks to the database or files, or assist with manual operational tasks during development phases.

---

## Testing Framework (`tests/`)

### `tests/test_interview_logic.py`
**Level:** Unit Testing (Core)
This massive test suite aggressively validates the AI state machine. It mocks LLM outputs to verify that the backend correctly escalates difficulty, tracks closed vs. open questions, detects bad answers, and computes final scores perfectly without hallucination.

### `tests/test_grounded_questions.py` & `tests/test_50_questions_validation.py`
**Level:** Quality Assurance (LLM)
These test files validate the output quality of the AI prompts. They run inference on known resumes to ensure the system generates strictly contextual (grounded) questions and does not drift into generic or hallucinatory topics.

### `tests/test_auth_identity.py` & `tests/test_email_validation.py`
**Level:** Unit Testing (Security)
These files ensure the security gates remain tightly shut. They verify that the backend accurately merges OAuth identities and successfully rejects known disposable/fake email domains to prevent platform abuse.

### `tests/fixtures/*.json`
**Level:** Test Data
These files hold mock responses, fake resumes, and structured payload examples. They allow the test suite to run rapidly and deterministically without needing a live database or paying for real API calls to external providers.

---
**Summary:** This concludes the comprehensive codebase documentation. Every file in the system contributes to building a defensive, scalable, and product-focused SaaS ecosystem.
"""
with open(r'C:\Users\ADMIN\.gemini\antigravity-ide\brain\07430001-d606-46f6-99b7-aeadc94d58a6\full_codebase_documentation.md', 'a', encoding='utf-8') as f:
    f.write(text)
