"""Generate a synthetic policy acceptance transcript; no network or user data.

Run from the repository root: python -m scripts.demo_interview_v2
"""
import json
from pathlib import Path

from app.services.interview_orchestrator import InterviewOrchestrator, build_blueprint, evidence_report

PROFILE = {"skills": ["Python", "FastAPI", "PostgreSQL", "Redis"], "projects": [{"name": "Placement project"}],
           "certifications": ["Python course"], "department": "CSE", "target_role": "Backend / Software Engineer"}
ANSWERS = {
    "intro": "I am a final-year CSE student interested in backend engineering. I built a placement project using Python, FastAPI and PostgreSQL with my team.",
    "project": "I implemented Redis caching for our placement project.",
    "technical": "I tested the endpoint with request logs and compared database timings because I needed to locate the delay. The tests showed repeated reads, and I learned to inspect the whole request path.",
    "ownership": "I took responsibility for a failing login flow because the release was blocked. I tested the token handling and fixed an expiry check. The tests passed and the team completed the release.",
    "failure": "I implemented caching too broadly and a test failed. I changed invalidation because updates could return old data. I tested the failure path again, and learned to document cache boundaries.",
    "ai": "I used AI-generated code to help with my implementation.",
    "pressure": "I organized the remaining tasks because two deadlines conflicted. I asked the team to prioritize the required features. We completed the core work and I learned to raise risks earlier.",
    "teamwork": "I asked a teammate to explain a different design because I wanted to understand the constraint. I compared both approaches with a small test. The feedback helped us reach a decision.",
    "role": "I enjoy tracing how requests turn into reliable data operations. I built the API layer in our project because I wanted to learn that responsibility, and I want to strengthen my testing skills.",
    "career": "I want to grow into an engineer who can own a reliable service and explain its trade-offs. I am still exploring which product domain I prefer.",
    "problem": "I compared the symptoms against a working request because the error message was unclear. I tested one assumption at a time and found a mismatch in the input format. The corrected request passed.",
    "closing": "What would a new backend engineer focus on learning during the first few months?",
}


def generate() -> tuple[list[dict], dict]:
    blueprint = build_blueprint(PROFILE, max_questions=24)
    state = InterviewOrchestrator.create(blueprint, PROFILE)
    state, question = InterviewOrchestrator.advance(state, remaining_seconds=1080, event="start")
    transcript = []
    while question:
        if question["type"] == "FOLLOWUP":
            answer = ("I cached repeated placement listing reads because they changed infrequently. I implemented invalidation on updates and a short expiry. I tested update and expiry paths and compared responses before and after; those tests passed."
                      if question["reason_for_asking"] == "reasoning" else
                      "I checked the library documentation and tested normal and failure cases before keeping the generated code. I reviewed the changes because a passing example alone does not establish correctness.")
        else:
            answer = ANSWERS.get(question["definition_id"], ANSWERS["problem"])
        transcript.append({"question": question, "answer": answer})
        state, question = InterviewOrchestrator.advance(state, answer, remaining_seconds=1080 - len(transcript) * 50)
    return transcript, evidence_report(state)


if __name__ == "__main__":
    transcript, report = generate()
    destination = Path(__file__).resolve().parents[1] / "docs" / "INTERVIEW_SAMPLE_TRANSCRIPT.md"
    lines = ["# Synthetic V2 acceptance transcript", "", "Generated by the deterministic policy, with fictional test answers. Not a real student or provider evaluation.", "",
             "The harness uses a 24-question allowance to demonstrate the requested standard blueprint. Production plan limits remain 5/10/13 total questions.", ""]
    for i, row in enumerate(transcript, 1):
        question = row["question"]
        lines.extend([f"## {i}. {question['type']} — {question['family']}", "", question["text"], "", f"Candidate: {row['answer']}", ""])
    lines.extend(["## Result", "", f"{report['primary_count']} primary questions; {report['followup_count']} targeted probes; partial={report['partial']}.", ""])
    destination.write_text("\n".join(lines), encoding="utf-8")
    print(json.dumps({"transcript": str(destination), "primary": report["primary_count"], "followups": report["followup_count"], "partial": report["partial"]}))
