'use client';
import { RolePath } from '@/components/role-path';
import { useWorkspace } from '@/lib/state';
import { challenges } from '@/lib/challenges';
import { progressFor } from '@/lib/progress';
import { PageHeading, Empty, ActionLink } from '@/components/ui';
export default function Progress() {
  const { state } = useWorkspace(); const done = new Set(state.attempts.filter(a => a.passed === a.total).map(a => a.challengeId));
  return <><PageHeading eyebrow="EVIDENCE, NOT GUESSWORK" title="Your work tells the story." description="Actual practice checks, recorded assistance, and the next step in your learning path." action={<ActionLink href="/settings" secondary>Export my work</ActionLink>}/><div className="stats-grid">{[['Problems solved', done.size], ['Independent passing attempts', state.attempts.filter(a => a.passed === a.total && !a.assisted).length], ['Practice attempts', state.attempts.length]].map(([title, value]) => <div className="stat-card" key={title}><div><strong>{value}</strong><span>{title}</span></div></div>)}</div>{!state.attempts.length && <Empty title="Your growth starts with your first attempt">Submit a coding challenge to create real evidence. No skill rating is assigned yet.</Empty>}<div className="section-header"><h2>Practice path</h2><span className="muted small">Foundations to application</span></div><div className="challenge-list">{challenges.map(c => { const { rows, estimate, growth } = progressFor(c.challengeId, state.attempts); return <section className="panel" key={c.challengeId}><div className="section-header"><div><span className={`tag ${done.has(c.challengeId) ? 'cyan' : ''}`}>{done.has(c.challengeId) ? 'Solved in practice' : rows.length ? 'Keep working' : 'Not attempted'}</span><h3>{c.title}</h3></div><ActionLink href={`/practice/${c.challengeId}`} secondary>{done.has(c.challengeId) ? 'Review' : 'Practise'}</ActionLink></div><p className="muted">{c.learningObjective}</p>{rows.length > 0 && <><progress max={100} value={estimate.masteryScore} aria-label={`${c.title} weighted practice score`}/><p className="small">{estimate.masteryScore.toFixed(0)}% weighted check score · {rows.length} attempts · {estimate.independentSuccessCount} independent successes</p><p className="muted tiny">Practice estimate from the PrepVista coding evidence model, weighted by difficulty, guidance and recency. One exercise cannot establish mastery.</p>{growth && <p className="small">{growth.unavailable ? `Trend unavailable: ${growth.reasons.map(r => r.toLowerCase().replaceAll('_', ' ')).join('; ')}` : `${growth.absoluteChange > 0 ? '+' : ''}${growth.absoluteChange} percentage points between the first and latest comparable three-attempt windows · ${growth.confidence.toLowerCase()} confidence`}</p>}</>}</section>; })}</div><RolePath/><section className="panel"><h2>Attempt history</h2>{state.attempts.length ? [...state.attempts].reverse().map(a => <details key={a.id}><summary>{challenges.find(c => c.challengeId === a.challengeId)?.title} · {a.passed}/{a.total} · {a.assisted ? 'Guided' : 'Independent'} · {new Date(a.at).toLocaleString()}</summary><pre>{a.code}</pre></details>) : <p className="muted">No submissions saved yet.</p>}<p className="muted tiny">The most recent 100 attempts are retained. Browser-local records are editable by their owner and are not verified assessment credentials.</p></section></>;
}
