'use client';
import { useState } from 'react';
import { Download, Upload, RotateCcw } from 'lucide-react';
import { useWorkspace, freshState, decodeState } from '@/lib/state';
import { PageHeading } from '@/components/ui';
export default function Settings() {
  const { state, update, replace } = useWorkspace(); const [notice, setNotice] = useState('');
  function exportWork() { const url = URL.createObjectURL(new Blob([JSON.stringify(state, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `coding-backup-${new Date().toISOString().slice(0, 10)}.json`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setNotice('Backup downloaded.'); }
  return <><PageHeading eyebrow="YOUR WORKSPACE, YOUR CHOICES" title="Keep your work close." description="No account needed. Manage your preferences and back up what you have learned."/><div className="settings-grid"><section className="panel"><h2>Learning preferences</h2><label className="field-label">Preferred programming language<select value={state.language} onChange={e => update(s => ({ ...s, language: e.target.value as typeof state.language }))}><option value="javascript">JavaScript · editing and execution</option><option value="python">Python · editing and mentoring</option><option value="java">Java · available starter and mentoring</option></select></label><p className="muted small">A challenge uses JavaScript when your preferred starter is unavailable.</p><h3>Local persistence</h3><p>Drafts, attempts, bookmarks, and notes are saved on this browser. They do not sync between devices. Clearing browser data removes them.</p><p>Only questions you submit to the mentor, with the related code and context, are sent to Gemini through the PrepVista server.</p></section><section className="panel"><h2>Backup and restore</h2><p className="muted">Export before switching browsers or clearing storage. Backups include your saved code and notes.</p><button className="button" onClick={exportWork}><Download size={16}/>Export workspace</button><label className="field-label upload-label"><span><Upload size={16}/>Restore a PrepVista coding backup</span><input type="file" accept="application/json,.json" onChange={async e => { const file = e.target.files?.[0]; if (!file) return; try { if (file.size > 4000000) throw new Error('Backup is too large.'); const imported = decodeState(await file.text()); if (window.confirm('Replace your current local workspace with this backup?')) { replace(imported); setNotice('Workspace restored.'); } } catch { setNotice('That file is not a valid PrepVista coding backup. Your current work is unchanged.'); } e.target.value = ''; }}/></label>{notice && <p className="notice" role="status">{notice}</p>}<hr/><h3>Start fresh</h3><p className="muted small">This clears only this PrepVista coding workspace. Export a backup first if you want to keep your work.</p><button className="button danger" onClick={() => { if (window.confirm('Clear all PrepVista coding drafts, notes, and progress in this browser?')) { replace(freshState()); setNotice('A fresh workspace is ready.'); } }}><RotateCcw size={15}/>Reset workspace</button></section></div></>;
}
