'use client';
import { useState } from 'react';
import { BookOpen, Check } from 'lucide-react';
import { competencies, skills } from '@/modules/coding/engines/catalog/seed/data';
import { challenges } from '@/modules/coding/lib/challenges';
import { useWorkspace } from '@/modules/coding/lib/state';
import { PageHeading, ActionLink, TextOutput } from '@/modules/coding/components/ui';
import { Mentor } from '@/modules/coding/components/mentor';
export default function Learn() {
  const { state, update } = useWorkspace(); const [topic, setTopic] = useState(competencies[0].slug as string); const [selected, setSelected] = useState(skills[0].slug);
  const skill = skills.find(s => s.slug === selected) ?? skills[0];
  const related = challenges.filter(c => `${c.skill} ${c.description} ${c.competencies.join(' ')}`.toLowerCase().includes(skill.name.split(' ')[0].toLowerCase()));
  const exercise = related[0];
  return <><PageHeading eyebrow="BUILD THE FOUNDATIONS" title="Understand it. Then put it to work." description="Explore the PrepVista coding skill map and connect each idea to your own reasoning."/><div className="learning-grid"><aside className="panel topic-panel"><label className="field-label">Competency<select value={topic} onChange={e => { setTopic(e.target.value); const first = skills.find(s => s.competency === e.target.value); if (first) setSelected(first.slug); }}>{competencies.map(c => <option key={c.slug} value={c.slug}>{c.name}</option>)}</select></label><nav aria-label="Concepts">{skills.filter(s => s.competency === topic).map(s => <button key={s.slug} aria-pressed={selected === s.slug} className={`topic-button ${selected === s.slug ? 'selected' : ''}`} onClick={() => setSelected(s.slug)}><BookOpen size={16}/>{s.name}{state.learned.includes(s.slug) && <Check size={15}/>}</button>)}</nav></aside><div><section className="panel lesson-panel"><span className="tag cyan">{skill.category.toLowerCase()}</span><h2>{skill.name}</h2><p className="lead">{skill.description}</p>{skill.parent && <p className="muted">Builds on: {skills.find(s => s.slug === skill.parent)?.name}</p>}<div className="next-step"><strong>Before asking for an explanation</strong><p>Describe where you would use this idea. Write one example and one edge case. What would you expect to happen?</p></div><label className="field-label">My understanding<textarea rows={5} maxLength={6000} value={state.notes[`learn:${skill.slug}`] ?? ''} onChange={e => update(s => ({ ...s, notes: { ...s.notes, [`learn:${skill.slug}`]: e.target.value } }))} placeholder="In my own words…"/></label><button className="button secondary" onClick={() => update(s => ({ ...s, learned: s.learned.includes(skill.slug) ? s.learned.filter(id => id !== skill.slug) : [...s.learned, skill.slug] }))}><Check size={16}/>{state.learned.includes(skill.slug) ? 'Explored · undo' : 'Mark as explored'}</button><p className="muted tiny">This is a reading checkpoint, not a mastery score.</p>{exercise && <div className="lesson-example"><h3>A related implementation pattern</h3><TextOutput text={exercise.solutionMetadata.approachSummary}/><p>{exercise.solutionMetadata.timeComplexity} · {exercise.solutionMetadata.spaceComplexity}</p><ActionLink href={`/coding/practice/${exercise.challengeId}`}>Practise this pattern</ActionLink></div>}</section><Mentor key={skill.slug} initialMode="concept" language="text" context={`${skill.name}: ${skill.description}\nStudent notes: ${state.notes[`learn:${skill.slug}`] ?? ''}`}/></div></div></>;
}
