export const PRIVACY_POLICY_TEXT = `**Privacy Policy**

**Effective Date:** March 22, 2026
**Last Updated:** March 22, 2026

PrepVista (â€œPrepVista,â€ â€œwe,â€ â€œus,â€ or â€œourâ€) is committed to protecting your privacy and handling personal information in a responsible, transparent, and secure manner. This Privacy Policy explains how we collect, receive, use, process, store, disclose, transfer, retain, and otherwise handle information when you access, visit, register for, interact with, or use our website, platform, applications, products, features, content, communications, and related services, including interview practice, personalized question generation, coaching, performance reporting, subscriptions, account management, customer support, and any related functionality we make available from time to time (collectively, the â€œServicesâ€). This Privacy Policy is intended to help you understand what information we collect, why we collect it, how we use it, when it may be shared, how long it may be retained, what rights and choices you may have, and how we seek to safeguard it. By accessing or using the Services, you acknowledge that you have read and understood this Privacy Policy and agree to the practices described in it, subject to applicable law.

We may collect information directly from you, automatically through your use of the Services, and in certain cases from authorized third parties or service providers. The information we collect depends on how you use PrepVista, the features you access, the information you choose to provide, the permissions you grant, and the transactions you complete. Information you provide directly may include your name, email address, account credentials, profile information, communication preferences, subscription choices, support messages, uploaded documents, feedback, form responses, and any other information or content you voluntarily submit through the Services. If you create an account, we may collect information necessary to establish, authenticate, maintain, and secure that account. If you choose to sign in through a third-party authentication provider, we may receive limited profile or account information associated with that provider, subject to the permissions you authorize and the settings of that provider.

As part of the Services, you may upload resumes, CVs, career documents, or similar materials for personalization and interview preparation purposes. When you submit such materials, we may collect, process, analyze, and store the content contained in those materials in order to provide and improve the Services. This may include information such as education history, professional experience, work samples, projects, skills, certifications, achievements, and other career-related details that you choose to include. We may use this information to tailor interview questions, personalize practice sessions, improve the relevance of feedback, adapt question difficulty or subject matter to your background, and provide outputs that are more closely aligned with your profile, goals, and experience. The quality and relevance of some features may depend in part on the accuracy, completeness, and appropriateness of the information you choose to provide.

When you participate in interview sessions, voice-based interactions, coaching flows, evaluation features, feedback modules, or related user experiences, we may collect and process information associated with those interactions. This may include prompts shown to you, answers you provide, transcripts derived from your responses, interview mode selections, timing information, categories of questions, evaluation results, scores, comparative performance insights, progress history, strengths and weaknesses identified by the system, recommendations, coaching feedback, and other session-related information. If a feature involves spoken responses, your spoken input may be converted into text and processed as part of the Services. If a feature requests access to your microphone or camera, such access is requested solely to provide that particular feature or user-selected functionality. Depending on the design of the specific feature, some information may be processed temporarily, locally, or in connection with the relevant session experience in order to support voice interaction, focus monitoring, realistic simulation, personalization, or related service functionality. We do not use camera or microphone access for purposes unrelated to delivering the feature you have chosen to use.

We may also collect technical, device, and usage information automatically when you use the Services. This may include browser type, device type, operating system, language settings, IP address, approximate location information inferred from technical data, timestamps, pages or screens viewed, features accessed, buttons clicked, referral information, session duration, authentication events, account activity, reports viewed or downloaded, interviews started or completed, plan usage, quota consumption, cookies, local storage data, session identifiers, logs, crash information, diagnostic data, and similar information. We collect and use this information to operate the Services, maintain security, authenticate users, preserve session integrity, detect suspicious activity, enforce subscription limits, monitor performance, troubleshoot problems, improve reliability, analyze usage trends, understand how features are used, refine product design, and support overall business operations. We may also generate aggregated, statistical, anonymized, or de-identified information derived from this data for analytics, reporting, research, benchmarking, testing, service optimization, and lawful business improvement purposes.

If you purchase a paid plan, subscription, or related offering, payment-related information may be processed by authorized payment providers in connection with the transaction. We do not store full card numbers, CVV information, or comparable highly sensitive payment credentials unless expressly stated otherwise. However, we may receive and retain limited billing and transaction-related details necessary to confirm payment, activate features, manage subscriptions, maintain records, provide billing support, issue invoices or confirmations, address disputes, prevent fraud, comply with legal obligations, and administer service access. Such information may include billing status, order references, payment identifiers, subscription tier, renewal status, timestamps, plan information, and related account records.

We use personal information for a variety of legitimate business, operational, legal, and service-related purposes. These purposes may include providing, operating, maintaining, supporting, securing, and improving the Services; creating and managing accounts; authenticating user access; personalizing interview questions, reports, and coaching experiences; generating evaluations, scores, recommendations, and feedback; enabling purchases, subscriptions, and billing administration; communicating with you regarding account activity, confirmations, reminders, support requests, security notices, policy updates, product updates, and service-related matters; monitoring compliance with our terms and usage limits; preventing fraud, abuse, misuse, unauthorized access, and security threats; investigating complaints, technical issues, or policy violations; conducting internal research, quality assurance, testing, auditing, analytics, and product improvement; complying with applicable legal, regulatory, tax, accounting, and contractual obligations; and protecting the rights, safety, systems, business operations, personnel, users, and property of PrepVista and others. We may also use aggregated, anonymized, or de-identified data for lawful business purposes, including service improvement, analytics, product planning, and performance evaluation.

We do not sell your personal information. We may share personal information with trusted service providers, contractors, consultants, partners, and vendors who perform functions on our behalf or support the operation of the Services, provided that such parties are permitted to access and use the information only as necessary to perform those functions or as otherwise permitted by law. These recipients may include providers involved in payment processing, communications delivery, customer support, hosting, storage, analytics, security, personalization, evaluation, fraud prevention, and related operational support. To deliver certain personalized or evaluation-based features, we may share relevant content such as resume information, prompts, transcripts, or session context with authorized processing providers where necessary to perform the Services you request. We may also disclose information within our corporate structure, to professional advisers, auditors, insurers, legal counsel, financial advisers, or similar parties where reasonably necessary for lawful business, financial, compliance, or legal purposes. In addition, we may disclose information if we believe such disclosure is necessary or appropriate to comply with applicable law, regulation, court order, subpoena, lawful governmental request, or legal process; to enforce our agreements, policies, or terms; to detect, prevent, investigate, or respond to fraud, abuse, security incidents, technical issues, or unlawful conduct; or to protect the rights, property, safety, or operations of PrepVista, our users, or others. If PrepVista is involved in a merger, acquisition, reorganization, restructuring, financing, dissolution, sale of assets, bankruptcy, or similar business transaction, personal information may be disclosed, transferred, or otherwise processed as part of that transaction, subject to applicable confidentiality and legal safeguards.

We retain personal information for as long as reasonably necessary for the purposes described in this Privacy Policy, including to provide the Services, maintain your account, preserve your interview history and reports, fulfill contractual obligations, comply with legal requirements, resolve disputes, enforce agreements, maintain security, support audits, preserve business records, and protect against fraud or misuse. Different categories of information may be retained for different periods depending on the reason for collection, the nature of the relationship, the sensitivity of the information, operational and legal requirements, and legitimate business needs. Account information may be retained while your account is active and for a reasonable period thereafter. Interview history, reports, transcripts, scores, and related data may be retained to allow continued access to prior sessions and progress history. Billing and transaction records may be retained for accounting, tax, compliance, fraud prevention, audit, and dispute resolution purposes. Support records may be retained to improve customer service and address recurring issues. When information is no longer reasonably necessary, we will take steps consistent with applicable law and operational needs to delete, anonymize, aggregate, archive, or otherwise securely handle it.

Depending on your jurisdiction and subject to applicable law, you may have certain rights and choices in relation to your personal information. These may include the right to request access to the personal information we hold about you, request correction of inaccurate or incomplete information, request deletion of your information, request restriction of certain processing, object to certain forms of processing, withdraw consent where consent is the relevant basis of processing, request portability of certain information where required by law and technically feasible, or request information regarding how your personal information has been collected, used, or disclosed. Some rights may be limited, conditional, or subject to exceptions under applicable law. To protect your privacy and account security, we may require you to verify your identity before responding to certain requests. In some circumstances, we may decline or limit a request where permitted by law, including where compliance would adversely affect the rights of others, interfere with legal obligations, undermine security or fraud prevention measures, involve disproportionate effort, or otherwise fall within a lawful exception.

If you request deletion of your account or personal information, we will review and process that request in accordance with applicable law and our legitimate operational obligations. Deletion may be permanent and irreversible, and once certain information is deleted it may not be recoverable. However, even after a deletion request, we may retain certain information where necessary to comply with legal obligations, preserve transaction and financial records, maintain security, investigate misconduct, resolve disputes, enforce our agreements, complete open transactions, prevent fraud, preserve backups for a limited cycle, or otherwise maintain information for lawful and legitimate business purposes. Any retained information will continue to be protected and used only as permitted by applicable law and this Privacy Policy.

We use reasonable administrative, technical, organizational, and physical safeguards designed to protect personal information from unauthorized access, loss, misuse, destruction, alteration, or disclosure. These safeguards may include access controls, authentication measures, encryption where appropriate, logging, monitoring, review procedures, vendor controls, security testing, incident response practices, and other measures intended to reduce risk and support the confidentiality, integrity, and availability of information. However, no method of storage, transmission, or electronic processing can be guaranteed to be completely secure. As a result, while we strive to protect your information using commercially reasonable safeguards, we cannot and do not guarantee absolute security. You are responsible for maintaining the confidentiality of your credentials, protecting your devices, and using strong and unique passwords or comparable security measures where available.

PrepVista is not intended for children under the age of 16, and we do not knowingly collect personal information from children under 16 without appropriate authorization where required by law. If we become aware that personal information has been collected from a child in violation of applicable law, we will take reasonable steps to investigate and, where appropriate, delete such information. Parents or guardians who believe that a child may have provided personal information to PrepVista may contact us so that we can review the matter.

If you access or use PrepVista from a jurisdiction different from the one in which our personnel, partners, service providers, or operations are located, your information may be transferred to, stored in, or processed in one or more jurisdictions where data protection and privacy laws may differ from those of your place of residence. By using the Services, and where permitted by law, you acknowledge that such transfers may occur for the purposes described in this Privacy Policy. Where required, we will take measures intended to provide appropriate safeguards for such transfers in accordance with applicable law.

PrepVista may use cookies, local storage, pixels, tags, session identifiers, and similar technologies to operate, secure, and improve the Services. These technologies may help us recognize your browser or device, keep you signed in, maintain secure sessions, remember preferences, measure usage, analyze traffic patterns, improve performance, support account and billing functionality, prevent abuse, and enhance the user experience. Some of these technologies may be operated by trusted third parties acting on our behalf or supporting related service functions. Your browser or device settings may allow you to manage certain preferences related to cookies or similar technologies, although disabling some of them may limit the availability, quality, security, or functionality of parts of the Services.

The Services may contain links to, integrations with, or features provided by third-party websites, platforms, tools, or services. This Privacy Policy does not apply to the privacy practices of those third parties, and PrepVista is not responsible for their content, policies, terms, or data practices. Your interactions with third-party services are governed by the applicable terms and privacy policies of those services. We encourage you to review any relevant third-party privacy notices before providing information to them or using integrated features.

We may revise or update this Privacy Policy from time to time to reflect changes in our Services, operations, legal requirements, risk environment, or business practices. When we do so, we will update the â€œLast Updatedâ€ date above and, where required by law or where otherwise appropriate, provide notice through the website, platform, email, in-product communication, or other reasonable means. The form, timing, and content of any notice may depend on the nature and significance of the changes. Your continued access to or use of the Services after an updated Privacy Policy becomes effective constitutes your acknowledgement of the revised policy and, to the extent permitted by law, your acceptance of it.

If you have questions, concerns, complaints, or requests regarding this Privacy Policy or our handling of personal information, you may contact us at **[support.prepvistaai@gmail.com](mailto:support.prepvistaai@gmail.com)**. We will review communications received and respond within a reasonable time, subject to the nature of the request, applicable law, and any identity verification requirements that may apply.

To the extent required by applicable law, this Privacy Policy is intended to supplement, and not limit, any rights you may have under relevant privacy, data protection, consumer protection, or electronic communications laws. If any provision of this Privacy Policy is found to be invalid or unenforceable, the remaining provisions will continue in full force and effect to the maximum extent permitted by law. In the event of any conflict between this Privacy Policy and a more specific privacy notice provided for a particular feature, promotion, jurisdiction, or user category, the more specific notice will govern to the extent of that conflict.

By continuing to use PrepVista, you acknowledge the importance of reviewing this Privacy Policy periodically and remaining informed about how your information is collected, used, and protected as our Services evolve.`;

export const TERMS_TEXT = `**Terms & Conditions**

**Effective Date:** March 22, 2026
**Last Updated:** March 22, 2026

These Terms & Conditions (â€œTermsâ€) govern your access to and use of PrepVista, including our website, platform, applications, products, content, features, subscriptions, reports, communications, and related services (collectively, the â€œServicesâ€). By accessing, registering for, purchasing, or using PrepVista, you agree to be bound by these Terms and by any policies or guidelines that are incorporated into them by reference. If you do not agree to these Terms, you must not access or use the Services. These Terms form a legally binding agreement between you and PrepVista. Where required by context, references to â€œPrepVista,â€ â€œwe,â€ â€œus,â€ or â€œourâ€ refer to the operator of the Services, and references to â€œyouâ€ or â€œyourâ€ refer to the individual or entity accessing or using the Services.

PrepVista is an AI-powered interview coaching and practice platform designed to help users prepare for interviews through personalized question generation, voice-based or text-based mock interview experiences, automated scoring, AI-generated feedback, ideal answer guidance, performance tracking, reports, and related practice tools. PrepVista is intended solely as a learning, preparation, and self-improvement service. The Services are provided for informational, educational, and practice purposes only. PrepVista does not provide employment services, recruitment services, hiring representation, placement services, professional career counseling, licensed advisory services, or guaranteed professional assessment. Any scores, recommendations, coaching, analyses, evaluations, reports, rankings, or ideal answers made available through the Services are generated or supported by automated systems and are intended only to assist you in practice and preparation. They do not constitute professional advice and should not be treated as a substitute for independent judgment, human review, recruiter feedback, or professional counseling.

By using the Services, you acknowledge and agree that PrepVista does not guarantee any specific outcome, including but not limited to employment, job offers, interview success, salary improvement, professional advancement, recruiter selection, admission, or any other career or educational result. Your success in an interview or hiring process depends on many factors beyond our control, including your actual skills, communication, experience, market conditions, recruiter expectations, competition, and third-party decisions. You understand and accept that any output generated through the Services may be incomplete, subjective, simulated, inaccurate, inconsistent, or affected by limitations of automated systems. You agree that you are solely responsible for evaluating how you use such output and for making your own decisions regarding your career, interviews, or professional conduct.

In order to use certain features of PrepVista, you may be required to create an account, provide registration information, maintain login credentials, or authenticate through an approved sign-in method. You agree to provide accurate, current, and complete information during registration and to keep such information updated as necessary. You are responsible for maintaining the confidentiality of your account credentials, restricting access to your devices, and all activities that occur under your account, whether or not authorized by you. You must notify us promptly if you believe your account, password, email, or login credentials have been compromised or used without authorization. We reserve the right to suspend, restrict, reclaim, or terminate accounts that we reasonably believe are insecure, misleading, fraudulent, inactive for extended periods where permitted, or used in violation of these Terms or applicable law.

You may use the Services only for lawful purposes and only in accordance with these Terms. You agree not to misuse the Services or assist, encourage, or permit any third party to do so. Without limitation, you must not use the Services to violate any law, regulation, or third-party right; impersonate another person or entity; submit false, misleading, or fraudulent information; attempt to gain unauthorized access to systems, networks, data, accounts, or features; probe, scan, test, or exploit vulnerabilities; interfere with or disrupt the integrity, security, performance, or availability of the Services; scrape, copy, harvest, extract, or collect data from the Services using automated or unauthorized means; reverse engineer, decompile, disassemble, replicate, or attempt to derive source code, models, prompts, underlying methods, or proprietary logic; upload malicious code, malware, viruses, corrupted files, or harmful data; submit prompt injections, adversarial inputs, or manipulative content intended to alter, exploit, or bypass system behavior; use the Services in a manner unrelated to legitimate interview practice or learning; create multiple accounts to evade restrictions, plan limits, enforcement actions, or payment obligations; share accounts, resell access, sublicense access, or provide the Services to others without authorization; reproduce, distribute, publish, display, sell, or commercially exploit reports, coaching content, generated answers, or other outputs except as expressly permitted by us; or use the Services in any way that could damage, disable, overburden, or impair our operations or those of any user or provider.

PrepVista may offer free and paid plans, subscriptions, quotas, usage-based features, premium content, enhanced reports, or limited-access functionality. Details of current plans, pricing, included features, usage limits, and plan differences may be presented on our website, pricing page, checkout flow, or account area. You acknowledge that features, limits, prices, eligibility criteria, and plan structures may change from time to time. Where applicable, we may provide notice of material pricing or plan changes before such changes take effect. Paid access will not be considered activated unless and until payment has been successfully received, confirmed, and verified in accordance with our procedures. We reserve the right to refuse, suspend, restrict, or revoke access to paid features in cases of failed payments, chargebacks, fraud concerns, abuse, suspected misuse, pricing errors, technical verification issues, or breaches of these Terms.

If you purchase a paid plan, you authorize the relevant payment processor to charge your selected payment method for the applicable fees, taxes, and charges associated with your chosen plan. Unless otherwise stated at the time of purchase, paid access begins when payment is successfully completed and verified and remains active for the access period shown for that plan, such as one month. Usage allowances, interview credits, feature quotas, or similar limits may reset at the start of each newly purchased access period or according to the plan terms then in effect. You are responsible for ensuring that your payment information remains current, valid, and authorized. If a payment cannot be completed, we may suspend or limit your access to paid features until payment is successfully resolved.

Unless otherwise required by applicable law, fees paid for subscriptions, premium features, reports, or access rights are generally non-refundable. However, we may, in our sole discretion or where required by law, provide refunds, credits, extensions, or other remedies in limited circumstances. A full refund may be considered where a valid request is made within a limited time from payment and there has been no meaningful use of the paid plan, no premium interview session has been started, no premium report has been generated or accessed, and no premium answer or similar paid benefit has been unlocked or consumed. Refunds may also be considered in cases of duplicate billing, accidental double charges, verified technical failures that materially prevented delivery of the paid service, or other exceptional situations determined by us. No refund may be available after meaningful usage of the paid plan has occurred, including where a paid interview has started, premium content has been generated or accessed, or paid features have been materially consumed. In situations where a monetary refund is not appropriate or required, we may choose, at our sole discretion, to provide account credits, bonus interview credits, billing adjustments, service extensions, or other alternative remedies. Nothing in this paragraph limits any non-waivable rights you may have under applicable consumer law.

If a paid access period ends and is not renewed through a new purchase, your account may revert to the free plan or lose access to paid features for that expired tier. The end of a paid access period does not automatically entitle you to a refund unless otherwise required by law or expressly stated by us. If you delete your account while a paid plan is active, you remain responsible for any charges already incurred.

You may request deletion of your account at any time through available settings or by contacting us where such functionality is not available directly. Account deletion may result in the permanent loss of your account, interview history, reports, transcripts, scores, billing references, personalized settings, and other associated information, and such deletion may be irreversible. We are not responsible for restoring deleted accounts or deleted data except where required by law or where we explicitly offer a restoration process. Even after account deletion, we may retain limited information where necessary for legal compliance, fraud prevention, dispute resolution, billing records, enforcement of these Terms, security, backup retention cycles, or other legitimate business and legal purposes.

All rights, title, and interest in and to the Services, including the software, design, layout, user interface, workflows, branding, logos, trademarks, service marks, compilations, website content, text, visual elements, scoring methods, structures, question-generation systems, evaluation logic, coaching frameworks, reports, templates, outputs, and all related intellectual property rights, are and shall remain the exclusive property of PrepVista or its licensors, except for content that you lawfully submit and rights that cannot be excluded by law. Subject to your compliance with these Terms, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable right to access and use the Services for your personal, internal, non-commercial interview practice and learning purposes only. You may not copy, adapt, modify, reproduce, republish, distribute, transmit, sell, license, display, mirror, frame, exploit, or create derivative works from the Services or any part of them except as expressly permitted by us in writing or as required by law. Any unauthorized use of the Services or of content generated through the Services may violate intellectual property laws and these Terms.

To the extent you submit, upload, enter, transmit, or otherwise provide any content, including resumes, text, answers, questions, feedback, forms, support inquiries, or other materials, you represent and warrant that you have the necessary rights to provide such content and that your submission does not violate any law, contract, confidentiality obligation, intellectual property right, privacy right, or other third-party right. You retain ownership of your original submitted content, subject to any rights necessary for us to provide the Services. By submitting content through the Services, you grant PrepVista a worldwide, non-exclusive, royalty-free, sublicensable, transferable, and limited license to host, store, reproduce, process, adapt, format, display, analyze, and use that content solely as necessary to operate, provide, maintain, improve, secure, and support the Services, enforce these Terms, comply with legal obligations, and carry out related business functions described in our Privacy Policy. This license continues for as long as reasonably necessary for those purposes, subject to applicable law and our retention practices.

Because PrepVista relies in part on automated systems and AI-assisted processes, you acknowledge that outputs generated through the Services, including interview questions, evaluations, scores, summaries, feedback, ideal answers, and recommendations, may contain inaccuracies, omissions, biases, inconsistencies, or content that may not be suitable for every context. You agree not to rely exclusively on the Services for critical career, legal, financial, educational, employment, or life decisions. PrepVista does not warrant that any output will be accurate, complete, reliable, current, unbiased, lawful, appropriate, recruiter-approved, or fit for your particular purpose. You are solely responsible for reviewing, verifying, adapting, and using any generated output according to your own judgment and circumstances.

PrepVista may suspend, restrict, disable, or terminate all or part of your access to the Services at any time, with or without notice, where we believe in good faith that such action is appropriate, including where you violate these Terms, create risk or possible legal exposure for us or others, fail to pay fees when due, initiate abusive chargebacks, misuse the Services, engage in fraud or suspicious activity, interfere with the operation of the Services, submit harmful or unlawful content, or where suspension is necessary for security, maintenance, legal compliance, or operational reasons. We also reserve the right to modify, discontinue, remove, limit, or replace any feature, content, plan, integration, or functionality at any time, temporarily or permanently, with or without notice, subject to applicable law.

The Services are provided on an â€œas isâ€ and â€œas availableâ€ basis, with all faults and without warranties of any kind except to the extent such warranties cannot be excluded under applicable law. To the maximum extent permitted by law, PrepVista disclaims all warranties, representations, and conditions, whether express, implied, statutory, or otherwise, including any implied warranties of merchantability, fitness for a particular purpose, title, non-infringement, availability, uninterrupted access, accuracy, completeness, reliability, quality, compatibility, security, or freedom from harmful components. We do not warrant that the Services will be uninterrupted, error-free, timely, secure, or free of defects, or that any issues will be corrected. We do not warrant that the Services or outputs will meet your expectations, requirements, hiring goals, or commercial objectives.

To the fullest extent permitted by law, PrepVista and its operator, affiliates, licensors, service providers, contractors, and representatives shall not be liable for any indirect, incidental, consequential, special, exemplary, punitive, or enhanced damages, or for any loss of profits, revenue, business, goodwill, data, use, opportunity, career prospects, interview outcomes, or other intangible losses, arising out of or relating to your access to or use of, or inability to access or use, the Services, even if advised of the possibility of such damages. To the fullest extent permitted by law, our total aggregate liability arising out of or relating to these Terms or the Services shall not exceed the amount actually paid by you to PrepVista for the Services in the three months preceding the event giving rise to the claim, or, if you have not paid us anything, a nominal amount to be determined as the minimum permitted under applicable law. Some jurisdictions do not allow certain limitations of liability, so some of these limitations may not apply to you to the extent prohibited by law.

You agree to defend, indemnify, and hold harmless PrepVista and its operator, affiliates, licensors, service providers, contractors, personnel, and representatives from and against any claims, actions, demands, liabilities, damages, judgments, settlements, losses, costs, and expenses, including reasonable legal and professional fees, arising out of or relating to your use or misuse of the Services, your submitted content, your violation of these Terms, your infringement of any intellectual property, privacy, or other right of any person or entity, your breach of any law or regulation, or your fraud, negligence, or wilful misconduct. We reserve the right, at our expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which case you agree to cooperate fully with our defense.

Your use of the Services is also subject to our Privacy Policy, which explains how we collect, use, disclose, and protect personal information. By using the Services, you acknowledge that you have read and understood the Privacy Policy. To the extent there is a conflict between these Terms and the Privacy Policy regarding service usage, these Terms will govern, while the Privacy Policy will govern issues specifically related to personal information handling, except where otherwise stated.

We may update, amend, or revise these Terms from time to time in order to reflect changes in the Services, pricing, legal requirements, risk considerations, technical developments, business practices, or operational needs. When we do so, we will update the â€œLast Updatedâ€ date above and may provide additional notice where required by law or where we consider it appropriate, including through email, website notice, account notification, or in-product messaging. Your continued access to or use of the Services after revised Terms become effective constitutes your acceptance of the updated Terms to the extent permitted by law. If you do not agree to the revised Terms, you must stop using the Services.

These Terms shall be governed by and construed in accordance with the laws of India, without regard to conflict of laws principles. Subject to applicable law, the courts having jurisdiction in the city or location of the operatorâ€™s registration or principal place of business in India shall have exclusive jurisdiction over any dispute, claim, or controversy arising out of or relating to these Terms or the Services. Nothing in these Terms prevents either party from seeking injunctive or equitable relief in any court of competent jurisdiction where necessary to protect intellectual property, confidential information, or enforceable legal rights.

If any provision of these Terms is found to be invalid, illegal, or unenforceable, that provision shall be enforced to the maximum extent permitted by law, and the remaining provisions shall remain in full force and effect. Our failure to enforce any provision of these Terms shall not operate as a waiver of that provision or of any other provision. You may not assign, transfer, sublicense, or delegate any rights or obligations under these Terms without our prior written consent. We may assign or transfer our rights and obligations under these Terms in connection with a merger, acquisition, restructuring, sale of assets, or by operation of law. These Terms, together with any policies or notices expressly incorporated by reference, constitute the entire agreement between you and PrepVista regarding the Services and supersede any prior or contemporaneous agreements, communications, representations, or understandings relating to the same subject matter.

If you have any questions, concerns, or requests regarding these Terms, you may contact PrepVista at **[support.prepvistaai@gmail.com](mailto:support.prepvistaai@gmail.com)**.`;
